// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_vision_wrapper.proto

package vision

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SSL_WrapperPacket struct {
	Detection            *SSL_DetectionFrame `protobuf:"bytes,1,opt,name=detection" json:"detection,omitempty"`
	Geometry             *SSL_GeometryData   `protobuf:"bytes,2,opt,name=geometry" json:"geometry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SSL_WrapperPacket) Reset()         { *m = SSL_WrapperPacket{} }
func (m *SSL_WrapperPacket) String() string { return proto.CompactTextString(m) }
func (*SSL_WrapperPacket) ProtoMessage()    {}
func (*SSL_WrapperPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b7471c3468a2e38, []int{0}
}

func (m *SSL_WrapperPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSL_WrapperPacket.Unmarshal(m, b)
}
func (m *SSL_WrapperPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSL_WrapperPacket.Marshal(b, m, deterministic)
}
func (m *SSL_WrapperPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSL_WrapperPacket.Merge(m, src)
}
func (m *SSL_WrapperPacket) XXX_Size() int {
	return xxx_messageInfo_SSL_WrapperPacket.Size(m)
}
func (m *SSL_WrapperPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SSL_WrapperPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SSL_WrapperPacket proto.InternalMessageInfo

func (m *SSL_WrapperPacket) GetDetection() *SSL_DetectionFrame {
	if m != nil {
		return m.Detection
	}
	return nil
}

func (m *SSL_WrapperPacket) GetGeometry() *SSL_GeometryData {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func init() {
	proto.RegisterType((*SSL_WrapperPacket)(nil), "SSL_WrapperPacket")
}

func init() {
	proto.RegisterFile("ssl_vision_wrapper.proto", fileDescriptor_3b7471c3468a2e38)
}

var fileDescriptor_3b7471c3468a2e38 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x2e, 0xce, 0x89,
	0x2f, 0xcb, 0x2c, 0xce, 0xcc, 0xcf, 0x8b, 0x2f, 0x2f, 0x4a, 0x2c, 0x28, 0x48, 0x2d, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x42, 0x92, 0x49, 0x49, 0x2d, 0x49, 0x4d, 0x2e, 0xc9, 0xcc,
	0xcf, 0x83, 0xca, 0x49, 0x22, 0xc9, 0xa5, 0xa7, 0xe6, 0xe7, 0xa6, 0x96, 0x14, 0x55, 0x42, 0xa4,
	0x94, 0x4a, 0xb9, 0x04, 0x83, 0x83, 0x7d, 0xe2, 0xc3, 0x21, 0x66, 0x05, 0x24, 0x26, 0x67, 0xa7,
	0x96, 0x08, 0x19, 0x72, 0x71, 0xc2, 0x8d, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd6,
	0x03, 0x29, 0x73, 0x81, 0x89, 0xba, 0x15, 0x25, 0xe6, 0xa6, 0x06, 0x21, 0x54, 0x09, 0xe9, 0x72,
	0x71, 0xc0, 0x4c, 0x96, 0x60, 0x02, 0xeb, 0x10, 0x04, 0xeb, 0x70, 0x87, 0x0a, 0xba, 0x24, 0x96,
	0x24, 0x06, 0xc1, 0x95, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x9f, 0x01, 0xab, 0xc8, 0x00,
	0x00, 0x00,
}
