// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_gc_state.proto

package state

import (
	fmt "fmt"
	geom "github.com/RoboCup-SSL/ssl-game-controller/internal/app/geom"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command_Type int32

const (
	Command_UNKNOWN        Command_Type = 0
	Command_HALT           Command_Type = 1
	Command_STOP           Command_Type = 2
	Command_NORMAL_START   Command_Type = 3
	Command_FORCE_START    Command_Type = 4
	Command_DIRECT         Command_Type = 5
	Command_INDIRECT       Command_Type = 6
	Command_KICKOFF        Command_Type = 7
	Command_PENALTY        Command_Type = 8
	Command_TIMEOUT        Command_Type = 9
	Command_BALL_PLACEMENT Command_Type = 10
)

var Command_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "HALT",
	2:  "STOP",
	3:  "NORMAL_START",
	4:  "FORCE_START",
	5:  "DIRECT",
	6:  "INDIRECT",
	7:  "KICKOFF",
	8:  "PENALTY",
	9:  "TIMEOUT",
	10: "BALL_PLACEMENT",
}

var Command_Type_value = map[string]int32{
	"UNKNOWN":        0,
	"HALT":           1,
	"STOP":           2,
	"NORMAL_START":   3,
	"FORCE_START":    4,
	"DIRECT":         5,
	"INDIRECT":       6,
	"KICKOFF":        7,
	"PENALTY":        8,
	"TIMEOUT":        9,
	"BALL_PLACEMENT": 10,
}

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return proto.EnumName(Command_Type_name, int32(x))
}

func (x *Command_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Command_Type_value, data, "Command_Type")
	if err != nil {
		return err
	}
	*x = Command_Type(value)
	return nil
}

func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{3, 0}
}

type State_Division int32

const (
	State_DIV_UNKNOWN State_Division = 0
	State_DIV_A       State_Division = 1
	State_DIV_B       State_Division = 2
)

var State_Division_name = map[int32]string{
	0: "DIV_UNKNOWN",
	1: "DIV_A",
	2: "DIV_B",
}

var State_Division_value = map[string]int32{
	"DIV_UNKNOWN": 0,
	"DIV_A":       1,
	"DIV_B":       2,
}

func (x State_Division) Enum() *State_Division {
	p := new(State_Division)
	*p = x
	return p
}

func (x State_Division) String() string {
	return proto.EnumName(State_Division_name, int32(x))
}

func (x *State_Division) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(State_Division_value, data, "State_Division")
	if err != nil {
		return err
	}
	*x = State_Division(value)
	return nil
}

func (State_Division) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{5, 0}
}

type State_GameEventBehavior int32

const (
	State_GAME_EVENT_BEHAVIOR_UNKNOWN  State_GameEventBehavior = 0
	State_GAME_EVENT_BEHAVIOR_ON       State_GameEventBehavior = 1
	State_GAME_EVENT_BEHAVIOR_MAJORITY State_GameEventBehavior = 2
	State_GAME_EVENT_BEHAVIOR_OFF      State_GameEventBehavior = 3
)

var State_GameEventBehavior_name = map[int32]string{
	0: "GAME_EVENT_BEHAVIOR_UNKNOWN",
	1: "GAME_EVENT_BEHAVIOR_ON",
	2: "GAME_EVENT_BEHAVIOR_MAJORITY",
	3: "GAME_EVENT_BEHAVIOR_OFF",
}

var State_GameEventBehavior_value = map[string]int32{
	"GAME_EVENT_BEHAVIOR_UNKNOWN":  0,
	"GAME_EVENT_BEHAVIOR_ON":       1,
	"GAME_EVENT_BEHAVIOR_MAJORITY": 2,
	"GAME_EVENT_BEHAVIOR_OFF":      3,
}

func (x State_GameEventBehavior) Enum() *State_GameEventBehavior {
	p := new(State_GameEventBehavior)
	*p = x
	return p
}

func (x State_GameEventBehavior) String() string {
	return proto.EnumName(State_GameEventBehavior_name, int32(x))
}

func (x *State_GameEventBehavior) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(State_GameEventBehavior_value, data, "State_GameEventBehavior")
	if err != nil {
		return err
	}
	*x = State_GameEventBehavior(value)
	return nil
}

func (State_GameEventBehavior) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{5, 1}
}

type YellowCard struct {
	Id                   *uint32            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CausedByGameEvent    *GameEvent         `protobuf:"bytes,2,opt,name=caused_by_game_event,json=causedByGameEvent" json:"caused_by_game_event,omitempty"`
	TimeRemaining        *duration.Duration `protobuf:"bytes,3,opt,name=time_remaining,json=timeRemaining" json:"time_remaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *YellowCard) Reset()         { *m = YellowCard{} }
func (m *YellowCard) String() string { return proto.CompactTextString(m) }
func (*YellowCard) ProtoMessage()    {}
func (*YellowCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{0}
}

func (m *YellowCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YellowCard.Unmarshal(m, b)
}
func (m *YellowCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YellowCard.Marshal(b, m, deterministic)
}
func (m *YellowCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YellowCard.Merge(m, src)
}
func (m *YellowCard) XXX_Size() int {
	return xxx_messageInfo_YellowCard.Size(m)
}
func (m *YellowCard) XXX_DiscardUnknown() {
	xxx_messageInfo_YellowCard.DiscardUnknown(m)
}

var xxx_messageInfo_YellowCard proto.InternalMessageInfo

func (m *YellowCard) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *YellowCard) GetCausedByGameEvent() *GameEvent {
	if m != nil {
		return m.CausedByGameEvent
	}
	return nil
}

func (m *YellowCard) GetTimeRemaining() *duration.Duration {
	if m != nil {
		return m.TimeRemaining
	}
	return nil
}

type RedCard struct {
	Id                   *uint32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CausedByGameEvent    *GameEvent `protobuf:"bytes,2,opt,name=caused_by_game_event,json=causedByGameEvent" json:"caused_by_game_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RedCard) Reset()         { *m = RedCard{} }
func (m *RedCard) String() string { return proto.CompactTextString(m) }
func (*RedCard) ProtoMessage()    {}
func (*RedCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{1}
}

func (m *RedCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedCard.Unmarshal(m, b)
}
func (m *RedCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedCard.Marshal(b, m, deterministic)
}
func (m *RedCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedCard.Merge(m, src)
}
func (m *RedCard) XXX_Size() int {
	return xxx_messageInfo_RedCard.Size(m)
}
func (m *RedCard) XXX_DiscardUnknown() {
	xxx_messageInfo_RedCard.DiscardUnknown(m)
}

var xxx_messageInfo_RedCard proto.InternalMessageInfo

func (m *RedCard) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RedCard) GetCausedByGameEvent() *GameEvent {
	if m != nil {
		return m.CausedByGameEvent
	}
	return nil
}

type Foul struct {
	Id                   *uint32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CausedByGameEvent    *GameEvent `protobuf:"bytes,2,opt,name=caused_by_game_event,json=causedByGameEvent" json:"caused_by_game_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Foul) Reset()         { *m = Foul{} }
func (m *Foul) String() string { return proto.CompactTextString(m) }
func (*Foul) ProtoMessage()    {}
func (*Foul) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{2}
}

func (m *Foul) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foul.Unmarshal(m, b)
}
func (m *Foul) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foul.Marshal(b, m, deterministic)
}
func (m *Foul) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foul.Merge(m, src)
}
func (m *Foul) XXX_Size() int {
	return xxx_messageInfo_Foul.Size(m)
}
func (m *Foul) XXX_DiscardUnknown() {
	xxx_messageInfo_Foul.DiscardUnknown(m)
}

var xxx_messageInfo_Foul proto.InternalMessageInfo

func (m *Foul) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Foul) GetCausedByGameEvent() *GameEvent {
	if m != nil {
		return m.CausedByGameEvent
	}
	return nil
}

type Command struct {
	Type                 *Command_Type `protobuf:"varint,1,req,name=type,enum=Command_Type" json:"type,omitempty"`
	ForTeam              *Team         `protobuf:"varint,2,opt,name=for_team,json=forTeam,enum=Team" json:"for_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{3}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetType() Command_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Command_UNKNOWN
}

func (m *Command) GetForTeam() Team {
	if m != nil && m.ForTeam != nil {
		return *m.ForTeam
	}
	return Team_UNKNOWN
}

type TeamInfo struct {
	Name                         *string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Goals                        *int32             `protobuf:"varint,2,opt,name=goals" json:"goals,omitempty"`
	Goalkeeper                   *int32             `protobuf:"varint,3,opt,name=goalkeeper" json:"goalkeeper,omitempty"`
	YellowCards                  []*YellowCard      `protobuf:"bytes,4,rep,name=yellow_cards,json=yellowCards" json:"yellow_cards,omitempty"`
	RedCards                     []*RedCard         `protobuf:"bytes,5,rep,name=red_cards,json=redCards" json:"red_cards,omitempty"`
	TimeoutsLeft                 *int32             `protobuf:"varint,6,opt,name=timeouts_left,json=timeoutsLeft" json:"timeouts_left,omitempty"`
	TimeoutTimeLeft              *duration.Duration `protobuf:"bytes,7,opt,name=timeout_time_left,json=timeoutTimeLeft" json:"timeout_time_left,omitempty"`
	OnPositiveHalf               *bool              `protobuf:"varint,8,opt,name=on_positive_half,json=onPositiveHalf" json:"on_positive_half,omitempty"`
	Fouls                        []*Foul            `protobuf:"bytes,9,rep,name=fouls" json:"fouls,omitempty"`
	BallPlacementFailures        *int32             `protobuf:"varint,10,opt,name=ball_placement_failures,json=ballPlacementFailures" json:"ball_placement_failures,omitempty"`
	BallPlacementFailuresReached *bool              `protobuf:"varint,11,opt,name=ball_placement_failures_reached,json=ballPlacementFailuresReached" json:"ball_placement_failures_reached,omitempty"`
	CanPlaceBall                 *bool              `protobuf:"varint,12,opt,name=can_place_ball,json=canPlaceBall" json:"can_place_ball,omitempty"`
	MaxAllowedBots               *int32             `protobuf:"varint,13,opt,name=max_allowed_bots,json=maxAllowedBots" json:"max_allowed_bots,omitempty"`
	BotSubstitutionIntent        *bool              `protobuf:"varint,14,opt,name=bot_substitution_intent,json=botSubstitutionIntent" json:"bot_substitution_intent,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}           `json:"-"`
	XXX_unrecognized             []byte             `json:"-"`
	XXX_sizecache                int32              `json:"-"`
}

func (m *TeamInfo) Reset()         { *m = TeamInfo{} }
func (m *TeamInfo) String() string { return proto.CompactTextString(m) }
func (*TeamInfo) ProtoMessage()    {}
func (*TeamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{4}
}

func (m *TeamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamInfo.Unmarshal(m, b)
}
func (m *TeamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamInfo.Marshal(b, m, deterministic)
}
func (m *TeamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamInfo.Merge(m, src)
}
func (m *TeamInfo) XXX_Size() int {
	return xxx_messageInfo_TeamInfo.Size(m)
}
func (m *TeamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TeamInfo proto.InternalMessageInfo

func (m *TeamInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TeamInfo) GetGoals() int32 {
	if m != nil && m.Goals != nil {
		return *m.Goals
	}
	return 0
}

func (m *TeamInfo) GetGoalkeeper() int32 {
	if m != nil && m.Goalkeeper != nil {
		return *m.Goalkeeper
	}
	return 0
}

func (m *TeamInfo) GetYellowCards() []*YellowCard {
	if m != nil {
		return m.YellowCards
	}
	return nil
}

func (m *TeamInfo) GetRedCards() []*RedCard {
	if m != nil {
		return m.RedCards
	}
	return nil
}

func (m *TeamInfo) GetTimeoutsLeft() int32 {
	if m != nil && m.TimeoutsLeft != nil {
		return *m.TimeoutsLeft
	}
	return 0
}

func (m *TeamInfo) GetTimeoutTimeLeft() *duration.Duration {
	if m != nil {
		return m.TimeoutTimeLeft
	}
	return nil
}

func (m *TeamInfo) GetOnPositiveHalf() bool {
	if m != nil && m.OnPositiveHalf != nil {
		return *m.OnPositiveHalf
	}
	return false
}

func (m *TeamInfo) GetFouls() []*Foul {
	if m != nil {
		return m.Fouls
	}
	return nil
}

func (m *TeamInfo) GetBallPlacementFailures() int32 {
	if m != nil && m.BallPlacementFailures != nil {
		return *m.BallPlacementFailures
	}
	return 0
}

func (m *TeamInfo) GetBallPlacementFailuresReached() bool {
	if m != nil && m.BallPlacementFailuresReached != nil {
		return *m.BallPlacementFailuresReached
	}
	return false
}

func (m *TeamInfo) GetCanPlaceBall() bool {
	if m != nil && m.CanPlaceBall != nil {
		return *m.CanPlaceBall
	}
	return false
}

func (m *TeamInfo) GetMaxAllowedBots() int32 {
	if m != nil && m.MaxAllowedBots != nil {
		return *m.MaxAllowedBots
	}
	return 0
}

func (m *TeamInfo) GetBotSubstitutionIntent() bool {
	if m != nil && m.BotSubstitutionIntent != nil {
		return *m.BotSubstitutionIntent
	}
	return false
}

type State struct {
	Stage                      *Referee_Stage                     `protobuf:"varint,1,opt,name=stage,enum=Referee_Stage" json:"stage,omitempty"`
	Command                    *Command                           `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	StageTimeElapsed           *duration.Duration                 `protobuf:"bytes,4,opt,name=stage_time_elapsed,json=stageTimeElapsed" json:"stage_time_elapsed,omitempty"`
	StageTimeLeft              *duration.Duration                 `protobuf:"bytes,5,opt,name=stage_time_left,json=stageTimeLeft" json:"stage_time_left,omitempty"`
	MatchTimeStart             *timestamp.Timestamp               `protobuf:"bytes,6,opt,name=match_time_start,json=matchTimeStart" json:"match_time_start,omitempty"`
	TeamState                  map[string]*TeamInfo               `protobuf:"bytes,8,rep,name=team_state,json=teamState" json:"team_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PlacementPos               *geom.Vector2                      `protobuf:"bytes,9,opt,name=placement_pos,json=placementPos" json:"placement_pos,omitempty"`
	NextCommand                *Command                           `protobuf:"bytes,10,opt,name=next_command,json=nextCommand" json:"next_command,omitempty"`
	CurrentActionTimeRemaining *duration.Duration                 `protobuf:"bytes,12,opt,name=current_action_time_remaining,json=currentActionTimeRemaining" json:"current_action_time_remaining,omitempty"`
	GameEvents                 []*GameEvent                       `protobuf:"bytes,13,rep,name=game_events,json=gameEvents" json:"game_events,omitempty"`
	ProposedGameEvents         []*ProposedGameEvent               `protobuf:"bytes,14,rep,name=proposed_game_events,json=proposedGameEvents" json:"proposed_game_events,omitempty"`
	Division                   *State_Division                    `protobuf:"varint,15,opt,name=division,enum=State_Division" json:"division,omitempty"`
	AutoContinue               *bool                              `protobuf:"varint,16,opt,name=auto_continue,json=autoContinue" json:"auto_continue,omitempty"`
	FirstKickoffTeam           *Team                              `protobuf:"varint,17,opt,name=first_kickoff_team,json=firstKickoffTeam,enum=Team" json:"first_kickoff_team,omitempty"`
	GameEventBehavior          map[string]State_GameEventBehavior `protobuf:"bytes,18,rep,name=game_event_behavior,json=gameEventBehavior" json:"game_event_behavior,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=State_GameEventBehavior"`
	XXX_NoUnkeyedLiteral       struct{}                           `json:"-"`
	XXX_unrecognized           []byte                             `json:"-"`
	XXX_sizecache              int32                              `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6a070b26c7dbbaf, []int{5}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetStage() Referee_Stage {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return Referee_NORMAL_FIRST_HALF_PRE
}

func (m *State) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *State) GetStageTimeElapsed() *duration.Duration {
	if m != nil {
		return m.StageTimeElapsed
	}
	return nil
}

func (m *State) GetStageTimeLeft() *duration.Duration {
	if m != nil {
		return m.StageTimeLeft
	}
	return nil
}

func (m *State) GetMatchTimeStart() *timestamp.Timestamp {
	if m != nil {
		return m.MatchTimeStart
	}
	return nil
}

func (m *State) GetTeamState() map[string]*TeamInfo {
	if m != nil {
		return m.TeamState
	}
	return nil
}

func (m *State) GetPlacementPos() *geom.Vector2 {
	if m != nil {
		return m.PlacementPos
	}
	return nil
}

func (m *State) GetNextCommand() *Command {
	if m != nil {
		return m.NextCommand
	}
	return nil
}

func (m *State) GetCurrentActionTimeRemaining() *duration.Duration {
	if m != nil {
		return m.CurrentActionTimeRemaining
	}
	return nil
}

func (m *State) GetGameEvents() []*GameEvent {
	if m != nil {
		return m.GameEvents
	}
	return nil
}

func (m *State) GetProposedGameEvents() []*ProposedGameEvent {
	if m != nil {
		return m.ProposedGameEvents
	}
	return nil
}

func (m *State) GetDivision() State_Division {
	if m != nil && m.Division != nil {
		return *m.Division
	}
	return State_DIV_UNKNOWN
}

func (m *State) GetAutoContinue() bool {
	if m != nil && m.AutoContinue != nil {
		return *m.AutoContinue
	}
	return false
}

func (m *State) GetFirstKickoffTeam() Team {
	if m != nil && m.FirstKickoffTeam != nil {
		return *m.FirstKickoffTeam
	}
	return Team_UNKNOWN
}

func (m *State) GetGameEventBehavior() map[string]State_GameEventBehavior {
	if m != nil {
		return m.GameEventBehavior
	}
	return nil
}

func init() {
	proto.RegisterEnum("Command_Type", Command_Type_name, Command_Type_value)
	proto.RegisterEnum("State_Division", State_Division_name, State_Division_value)
	proto.RegisterEnum("State_GameEventBehavior", State_GameEventBehavior_name, State_GameEventBehavior_value)
	proto.RegisterType((*YellowCard)(nil), "YellowCard")
	proto.RegisterType((*RedCard)(nil), "RedCard")
	proto.RegisterType((*Foul)(nil), "Foul")
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterType((*TeamInfo)(nil), "TeamInfo")
	proto.RegisterType((*State)(nil), "State")
	proto.RegisterMapType((map[string]State_GameEventBehavior)(nil), "State.GameEventBehaviorEntry")
	proto.RegisterMapType((map[string]*TeamInfo)(nil), "State.TeamStateEntry")
}

func init() {
	proto.RegisterFile("ssl_gc_state.proto", fileDescriptor_d6a070b26c7dbbaf)
}

var fileDescriptor_d6a070b26c7dbbaf = []byte{
	// 1277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x6e, 0xdb, 0xb6,
	0x17, 0xfe, 0xd9, 0xb1, 0x1b, 0xfb, 0xd8, 0x51, 0x14, 0xb6, 0x69, 0xf5, 0x4b, 0xff, 0x24, 0xf3,
	0x3a, 0x20, 0x40, 0x11, 0x05, 0xf3, 0x86, 0x61, 0xd8, 0x30, 0x6c, 0xb6, 0x23, 0xa7, 0x5e, 0x1c,
	0xdb, 0xa0, 0xd5, 0x0c, 0x1d, 0x86, 0x11, 0xb4, 0x4c, 0x39, 0x42, 0x24, 0x51, 0x90, 0xa8, 0xac,
	0x7e, 0x8a, 0x3d, 0xc0, 0x2e, 0xf6, 0x3e, 0x7b, 0x8f, 0xdd, 0xef, 0x11, 0x06, 0x52, 0x92, 0xe3,
	0xa5, 0x29, 0x72, 0xd3, 0xbb, 0xc3, 0xef, 0x9c, 0xef, 0xf0, 0xf0, 0xf0, 0xe3, 0x21, 0xa0, 0x24,
	0xf1, 0xc9, 0xc2, 0x21, 0x89, 0xa0, 0x82, 0x99, 0x51, 0xcc, 0x05, 0xdf, 0x7b, 0x98, 0x63, 0x0e,
	0x0f, 0x02, 0x1e, 0xe6, 0xe0, 0x6e, 0x0e, 0x2e, 0x18, 0x0f, 0x98, 0x88, 0x97, 0x39, 0xfc, 0xa4,
	0x80, 0x69, 0xc0, 0x08, 0xbb, 0x66, 0xa1, 0xc8, 0x1d, 0xcf, 0x72, 0x47, 0xcc, 0x5c, 0x16, 0x33,
	0x46, 0x02, 0x96, 0x24, 0x74, 0x51, 0x6c, 0xf1, 0x62, 0xc1, 0xf9, 0xc2, 0x67, 0xc7, 0x6a, 0x35,
	0x4b, 0xdd, 0xe3, 0x79, 0x1a, 0x53, 0xe1, 0xad, 0x76, 0xdb, 0xbf, 0xed, 0x17, 0x5e, 0xc0, 0x12,
	0x41, 0x83, 0x28, 0x0b, 0x68, 0xfd, 0x51, 0x02, 0x78, 0xcb, 0x7c, 0x9f, 0xff, 0xd6, 0xa3, 0xf1,
	0x1c, 0x69, 0x50, 0xf6, 0xe6, 0x46, 0xe9, 0xa0, 0x74, 0xb8, 0x85, 0xcb, 0xde, 0x1c, 0x7d, 0x0b,
	0x8f, 0x1c, 0x9a, 0x26, 0x6c, 0x4e, 0x66, 0xcb, 0xb5, 0xda, 0x8c, 0xf2, 0x41, 0xe9, 0xb0, 0xd1,
	0x06, 0xf3, 0x94, 0x06, 0xcc, 0x92, 0x08, 0xde, 0xc9, 0xe2, 0xba, 0xcb, 0x15, 0x84, 0x7e, 0x00,
	0x4d, 0x6e, 0x47, 0x62, 0x16, 0x50, 0x2f, 0xf4, 0xc2, 0x85, 0xb1, 0xa1, 0x68, 0xff, 0x37, 0xb3,
	0xaa, 0xcc, 0xa2, 0x2a, 0xf3, 0x24, 0xaf, 0x1a, 0x6f, 0x49, 0x02, 0x2e, 0xe2, 0x5b, 0x17, 0xb0,
	0x89, 0xd9, 0xfc, 0xa3, 0x57, 0xd6, 0x9a, 0x42, 0xa5, 0xcf, 0x53, 0xff, 0xe3, 0x26, 0xfd, 0xa7,
	0x04, 0x9b, 0x3d, 0x1e, 0x04, 0x34, 0x9c, 0xa3, 0x4f, 0xa0, 0x22, 0x96, 0x11, 0x33, 0x4a, 0x07,
	0xe5, 0x43, 0xad, 0xbd, 0x65, 0xe6, 0xb8, 0x69, 0x2f, 0x23, 0x86, 0x95, 0x0b, 0x1d, 0x40, 0xcd,
	0xe5, 0x31, 0x11, 0x8c, 0x06, 0x2a, 0xbf, 0xd6, 0xae, 0x9a, 0x36, 0xa3, 0x01, 0xde, 0x74, 0x79,
	0x2c, 0x8d, 0xd6, 0x9f, 0x25, 0xa8, 0x48, 0x02, 0x6a, 0xc0, 0xe6, 0x9b, 0xd1, 0xd9, 0x68, 0xfc,
	0xd3, 0x48, 0xff, 0x1f, 0xaa, 0x41, 0xe5, 0x75, 0x67, 0x68, 0xeb, 0x25, 0x69, 0x4d, 0xed, 0xf1,
	0x44, 0x2f, 0x23, 0x1d, 0x9a, 0xa3, 0x31, 0x3e, 0xef, 0x0c, 0xc9, 0xd4, 0xee, 0x60, 0x5b, 0xdf,
	0x40, 0xdb, 0xd0, 0xe8, 0x8f, 0x71, 0xcf, 0xca, 0x81, 0x0a, 0x02, 0x78, 0x70, 0x32, 0xc0, 0x56,
	0xcf, 0xd6, 0xab, 0xa8, 0x09, 0xb5, 0xc1, 0x28, 0x5f, 0x3d, 0x90, 0xd9, 0xcf, 0x06, 0xbd, 0xb3,
	0x71, 0xbf, 0xaf, 0x6f, 0xca, 0xc5, 0xc4, 0x1a, 0x75, 0x86, 0xf6, 0x5b, 0xbd, 0x26, 0x17, 0xf6,
	0xe0, 0xdc, 0x1a, 0xbf, 0xb1, 0xf5, 0x3a, 0x42, 0xa0, 0x75, 0x3b, 0xc3, 0x21, 0x99, 0x0c, 0x3b,
	0x3d, 0xeb, 0xdc, 0x1a, 0xd9, 0x3a, 0xb4, 0xfe, 0xae, 0x40, 0x4d, 0x96, 0x3a, 0x08, 0x5d, 0x8e,
	0x10, 0x54, 0x42, 0x1a, 0x30, 0xd5, 0xce, 0x3a, 0x56, 0x36, 0x7a, 0x04, 0xd5, 0x05, 0xa7, 0x7e,
	0xa2, 0x4e, 0x58, 0xc5, 0xd9, 0x02, 0xbd, 0x00, 0x90, 0xc6, 0x15, 0x63, 0x11, 0x8b, 0x95, 0x28,
	0xaa, 0x78, 0x0d, 0x41, 0x26, 0x34, 0x97, 0x4a, 0x93, 0xc4, 0xa1, 0xf1, 0x3c, 0x31, 0x2a, 0x07,
	0x1b, 0x87, 0x8d, 0x76, 0xc3, 0xbc, 0x11, 0x2a, 0x6e, 0x2c, 0x57, 0x76, 0x82, 0x3e, 0x83, 0x7a,
	0xcc, 0xe6, 0x79, 0x70, 0x55, 0x05, 0xd7, 0xcc, 0x5c, 0x38, 0xb8, 0x16, 0x67, 0x46, 0x82, 0x3e,
	0x05, 0x25, 0x2f, 0x9e, 0x8a, 0x84, 0xf8, 0xcc, 0x15, 0xc6, 0x03, 0xb5, 0x73, 0xb3, 0x00, 0x87,
	0xcc, 0x15, 0xc8, 0x82, 0x9d, 0x7c, 0x4d, 0x94, 0x78, 0x55, 0xe0, 0xe6, 0x7d, 0xba, 0xdd, 0xce,
	0x39, 0xb6, 0x17, 0x30, 0x95, 0xe6, 0x10, 0x74, 0x1e, 0x92, 0x88, 0x27, 0x9e, 0xf0, 0xae, 0x19,
	0xb9, 0xa4, 0xbe, 0x6b, 0xd4, 0x0e, 0x4a, 0x87, 0x35, 0xac, 0xf1, 0x70, 0x92, 0xc3, 0xaf, 0xa9,
	0xef, 0xa2, 0xa7, 0x50, 0x75, 0x79, 0xea, 0x27, 0x46, 0x5d, 0x15, 0x5e, 0x35, 0xa5, 0x32, 0x71,
	0x86, 0xa1, 0xaf, 0xe0, 0xc9, 0x8c, 0xfa, 0x3e, 0x89, 0x7c, 0xea, 0xb0, 0x80, 0x85, 0x82, 0xb8,
	0xd4, 0xf3, 0xd3, 0x98, 0x25, 0x06, 0xa8, 0xe2, 0x77, 0xa5, 0x7b, 0x52, 0x78, 0xfb, 0xb9, 0x13,
	0x59, 0xb0, 0xff, 0x01, 0x1e, 0x89, 0x19, 0x75, 0x2e, 0xd9, 0xdc, 0x68, 0xa8, 0x6a, 0x9e, 0xdd,
	0xc9, 0xc7, 0x59, 0x0c, 0x7a, 0x09, 0x9a, 0x43, 0xc3, 0x2c, 0x0b, 0x91, 0x91, 0x46, 0x53, 0xb1,
	0x9a, 0x0e, 0x0d, 0x15, 0xa9, 0x4b, 0x7d, 0x5f, 0x9e, 0x35, 0xa0, 0xef, 0x08, 0x95, 0x17, 0x22,
	0x9f, 0x0e, 0x17, 0x89, 0xb1, 0xa5, 0xaa, 0xd3, 0x02, 0xfa, 0xae, 0x93, 0xc1, 0x5d, 0x2e, 0xb2,
	0xe3, 0x70, 0x41, 0x92, 0x74, 0x96, 0x08, 0x4f, 0xa4, 0xb2, 0x75, 0xc4, 0x0b, 0x85, 0x7c, 0x62,
	0x9a, 0x4a, 0xbc, 0x3b, 0xe3, 0x62, 0xba, 0xe6, 0x1d, 0x28, 0x67, 0xeb, 0xaf, 0x3a, 0x54, 0xa7,
	0x72, 0xb2, 0xa2, 0x97, 0x50, 0x4d, 0x04, 0x5d, 0x64, 0x2a, 0xd3, 0xda, 0x9a, 0x89, 0xb3, 0xb9,
	0x68, 0x4e, 0x25, 0x8a, 0x33, 0x27, 0x6a, 0xc1, 0xa6, 0x93, 0xbd, 0xb8, 0xfc, 0xe9, 0xd6, 0x8a,
	0x17, 0x88, 0x0b, 0x07, 0x3a, 0x05, 0xa4, 0x82, 0xb3, 0x6b, 0x66, 0x3e, 0x8d, 0x12, 0x36, 0x37,
	0x2a, 0xf7, 0xdd, 0xb4, 0xae, 0x48, 0xf2, 0x9e, 0xad, 0x8c, 0x82, 0x3a, 0xb0, 0xbd, 0x96, 0x48,
	0xe9, 0xa5, 0x7a, 0xef, 0x9c, 0x5b, 0x65, 0x51, 0x6a, 0x39, 0x91, 0x1d, 0x14, 0xce, 0x65, 0x96,
	0x22, 0x11, 0x34, 0xce, 0xc4, 0xd9, 0x68, 0xef, 0xbd, 0x97, 0xc3, 0x2e, 0x26, 0xb8, 0xec, 0xae,
	0x70, 0x2e, 0xe5, 0x7a, 0x2a, 0x19, 0xe8, 0x4b, 0x00, 0x39, 0x4d, 0xb2, 0x3f, 0xc8, 0xa8, 0x29,
	0x39, 0xed, 0x9a, 0xaa, 0x6f, 0x6a, 0xb2, 0x28, 0xcb, 0x0a, 0x45, 0xbc, 0xc4, 0x75, 0x51, 0xac,
	0xd1, 0x11, 0x6c, 0xdd, 0xa8, 0x24, 0xe2, 0x52, 0x87, 0x59, 0xc7, 0x2e, 0x98, 0x23, 0x78, 0xdc,
	0xc6, 0xcd, 0x95, 0x7b, 0xc2, 0x13, 0xf4, 0x0a, 0x9a, 0x21, 0x7b, 0x27, 0x48, 0xd1, 0x5f, 0xb8,
	0xd5, 0xdf, 0x86, 0xf4, 0x16, 0x63, 0xf0, 0x17, 0x78, 0xee, 0xa4, 0x71, 0x2c, 0x33, 0x53, 0x47,
	0xdd, 0xf6, 0xad, 0x0f, 0xa1, 0x79, 0x5f, 0xa3, 0xf6, 0x72, 0x7e, 0x47, 0xd1, 0xed, 0xf5, 0xdf,
	0x01, 0xbd, 0x82, 0xc6, 0xcd, 0x8c, 0x96, 0x92, 0xdb, 0xb8, 0x35, 0xa4, 0x61, 0x51, 0x98, 0x09,
	0x3a, 0x81, 0x47, 0x51, 0xcc, 0x23, 0x2e, 0x87, 0xfb, 0x3a, 0x4b, 0x53, 0x2c, 0x64, 0x4e, 0x72,
	0xe7, 0x0d, 0x1b, 0x45, 0xb7, 0x21, 0x79, 0xfa, 0xda, 0xdc, 0xbb, 0xf6, 0x12, 0x8f, 0x87, 0xc6,
	0xb6, 0x52, 0xe0, 0x76, 0xde, 0xe0, 0x93, 0x1c, 0xc6, 0xab, 0x00, 0x39, 0x6f, 0x68, 0x2a, 0x38,
	0x71, 0x78, 0x28, 0xbc, 0x30, 0x65, 0x86, 0x9e, 0x3d, 0x1e, 0x09, 0xf6, 0x72, 0x0c, 0x7d, 0x01,
	0xc8, 0xf5, 0xe2, 0x44, 0x90, 0x2b, 0xcf, 0xb9, 0xe2, 0xae, 0x9b, 0x7d, 0x08, 0x3b, 0xeb, 0x1f,
	0x82, 0xae, 0x02, 0xce, 0x32, 0xbf, 0x44, 0xd0, 0x39, 0x3c, 0xbc, 0x39, 0x03, 0x99, 0xb1, 0x4b,
	0x7a, 0xed, 0xf1, 0xd8, 0x40, 0xea, 0x2c, 0xcf, 0xf3, 0x8a, 0x56, 0x65, 0x77, 0x73, 0x7f, 0x76,
	0xf5, 0x3b, 0x8b, 0xdb, 0xf8, 0xde, 0x29, 0x68, 0xff, 0xd5, 0x07, 0xd2, 0x61, 0xe3, 0x8a, 0x2d,
	0xf3, 0x51, 0x2e, 0x4d, 0xb4, 0x0f, 0xd5, 0x6b, 0xea, 0xa7, 0x2c, 0x7f, 0x50, 0x75, 0xb3, 0x98,
	0xfb, 0x38, 0xc3, 0xbf, 0x29, 0x7f, 0x5d, 0xda, 0xfb, 0x15, 0x1e, 0xdf, 0xbd, 0xeb, 0x1d, 0x09,
	0xcd, 0xf5, 0x84, 0x5a, 0xdb, 0xf8, 0x50, 0xd5, 0x6b, 0xf9, 0x5b, 0x9f, 0x43, 0xad, 0xe8, 0xb3,
	0xfc, 0xe1, 0x4e, 0x06, 0x17, 0xe4, 0xe6, 0x63, 0xac, 0x43, 0x55, 0x02, 0x1d, 0xbd, 0x54, 0x98,
	0x5d, 0xbd, 0xdc, 0xfa, 0xbd, 0x04, 0x3b, 0xef, 0xe5, 0x44, 0xfb, 0xf0, 0xf4, 0xb4, 0x73, 0x6e,
	0x11, 0xeb, 0xc2, 0x1a, 0xd9, 0xa4, 0x6b, 0xbd, 0xee, 0x5c, 0x0c, 0xc6, 0x78, 0x2d, 0xd9, 0x1e,
	0x3c, 0xbe, 0x2b, 0x60, 0x3c, 0xd2, 0x4b, 0xe8, 0x00, 0x9e, 0xdd, 0xe5, 0x3b, 0xef, 0xfc, 0x38,
	0xc6, 0x03, 0xfb, 0xad, 0x5e, 0x46, 0x4f, 0xe1, 0xc9, 0x9d, 0xec, 0x7e, 0x5f, 0xdf, 0xe8, 0x7e,
	0xff, 0xf3, 0x77, 0x0b, 0x4f, 0x5c, 0xa6, 0x33, 0xd3, 0xe1, 0xc1, 0x31, 0xe6, 0x33, 0xde, 0x4b,
	0xa3, 0xa3, 0xe9, 0x74, 0x78, 0x9c, 0x24, 0xfe, 0x91, 0xbc, 0x9d, 0x23, 0xa9, 0x98, 0x98, 0xfb,
	0x3e, 0x8b, 0x8f, 0xe5, 0x78, 0x8c, 0x43, 0xea, 0x1f, 0xd3, 0x28, 0x3a, 0x56, 0x2f, 0xfb, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x9d, 0x5f, 0x60, 0x6c, 0x0a, 0x00, 0x00,
}
