@startuml
E->SM: GameEvent: BallLeftField
SM->SM: Command: Stop
alt no placement required
    E->SM: GameEvent: Prepared
    SM->SM: Command: NextCommand
else  placement
    E-> SM: Command: BallPlacement
    alt successful placement
        E->SM: GameEvent: BallPlacementSuccessful
        alt successful by team in favor
            SM->SM: Command: NextCommand
        else successful by opponent DivB team
            SM->SM: Command: Stop
            E->SM: GameEvent: Prepared
            SM->SM: Command: NextCommand
        else last event was result of ball leaving the field
            SM->SM: Command: Stop
            E->SM: GameEvent: Prepared
            SM->SM: Command: FreeKick for opponent team
        else placement successful by opponent DivA team
            SM->SM: Command: Stop
            E->SM: GameEvent: Prepared
            SM->SM: Command: FreeKick for opponent team
        end
    else failed placement
        E->SM: GameEvent: BallPlacementFailed
        SM->SM:
        alt other team can place the ball
            SM->SM: Command: BallPlacement
        else
            SM->SM: Command: Stop
        end
    end
end
@enduml

Case 1: DivB team disabled placement
When ball placement disabled, then opponent places ball, but team brings ball into play
Note: can also just be evaluated by the disabled flag (which should not be set by failure counter

Case 2: Placement Failure Counter == 5
Placement by opponent team if ball left the field
Manual otherwise

Case 3: Placement failed
1st: opponent team gets a free kick and places the ball
2nd: halt

Trigger: start placement for team A
if both teams cant do placement:
    halt
else if placement disabled for team A:
    next command for team A
    placement for team B
else if counter team A == 5:
    if ball left field:
        next command is free kick for team B
        placement for team B
    else:
        halt
else:
    placement for team A

Trigger: placement failed by team A
if allTeamsFailedPlacement():
    halt
else:
    next command for team B
    placement for team B

Trigger: placement succeeded by team A
if next command for team A:
    next command
else:
    stop



