@startuml

Team->Controller: establish TCP connection
Controller->Controller: generate new token
Controller->Team: ControllerReply ( token )
Team->Controller: TeamRegistration ( teamName, [ token, signature ] )
Controller-->Controller: verify token
Controller-->Controller: verify signature
Controller->Team: ControllerReply ( ok | reject )

loop
alt team requests a change
Team->Controller: TeamToController
Controller->Team: ControllerReply ( ok | reject )
else controller requests a decision
Controller->Team: ControllerToTeam
Team->Controller: TeamToController
Controller->Team: ControllerReply ( ok | reject )
end
end

@enduml
