{
  "gameEventBehavior": {
    "AIMLESS_KICK": "BEHAVIOR_ACCEPT_MAJORITY",
    "ATTACKER_DOUBLE_TOUCHED_BALL": "BEHAVIOR_ACCEPT_MAJORITY",
    "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA": "BEHAVIOR_ACCEPT_MAJORITY",
    "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA": "BEHAVIOR_ACCEPT_MAJORITY",
    "BALL_LEFT_FIELD_GOAL_LINE": "BEHAVIOR_ACCEPT_MAJORITY",
    "BALL_LEFT_FIELD_TOUCH_LINE": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_CRASH_DRAWN": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_CRASH_UNIQUE": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_DRIBBLED_BALL_TOO_FAR": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_HELD_BALL_DELIBERATELY": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_INTERFERED_PLACEMENT": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_KICKED_BALL_TOO_FAST": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_PUSHED_BOT": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_TIPPED_OVER": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_TOO_FAST_IN_STOP": "BEHAVIOR_ACCEPT_MAJORITY",
    "BOUNDARY_CROSSING": "BEHAVIOR_ACCEPT_MAJORITY",
    "DEFENDER_IN_DEFENSE_AREA": "BEHAVIOR_ACCEPT_MAJORITY",
    "DEFENDER_TOO_CLOSE_TO_KICK_POINT": "BEHAVIOR_ACCEPT_MAJORITY",
    "GOAL": "BEHAVIOR_ACCEPT_MAJORITY",
    "INVALID_GOAL": "BEHAVIOR_ACCEPT_MAJORITY",
    "KEEPER_HELD_BALL": "BEHAVIOR_ACCEPT_MAJORITY",
    "NO_PROGRESS_IN_GAME": "BEHAVIOR_ACCEPT_MAJORITY",
    "PENALTY_KICK_FAILED": "BEHAVIOR_ACCEPT_MAJORITY",
    "PLACEMENT_SUCCEEDED": "BEHAVIOR_ACCEPT_MAJORITY",
    "POSSIBLE_GOAL": "BEHAVIOR_ACCEPT_MAJORITY",
    "TOO_MANY_ROBOTS": "BEHAVIOR_ACCEPT_MAJORITY"
  },
  "autoRefConfigs": {
  },
  "teams": [
    "Unknown",
    "AIS",
    "AMC",
    "CMμs",
    "ER-Force",
    "Immortals",
    "ITAndroids",
    "KgpKubs",
    "KIKS",
    "luhbots",
    "MCT Susano Logics",
    "MIT Roboteam",
    "MRL",
    "nAMeC",
    "NAELIC",
    "NEUIslanders",
    "OMID",
    "OP-AmP",
    "Parsian",
    "Ri-One",
    "RFC Cambridge",
    "RobôCin",
    "RoboDragons",
    "RoboFEI",
    "RoboIME",
    "RoboJackets",
    "RoboTeam Twente",
    "SRC",
    "SSH",
    "STOx’s",
    "Sysmic Robotics",
    "Test Team",
    "TIGERs Mannheim",
    "Tritons RCSC",
    "ULtron",
    "UMass Minutebots",
    "UBC Thunderbots",
    "URoboRus",
    "Warthog Robotics",
    "ZJUNlict"
  ]
}
