// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_game_controller_auto_ref.proto

package rcon

import (
	fmt "fmt"
	state "github.com/RoboCup-SSL/ssl-game-controller/internal/app/state"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AutoRefRegistration is the first message that a client must send to the controller to identify itself
type AutoRefRegistration struct {
	// identifier is a unique name of the client
	Identifier *string `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	// signature can optionally be specified to enable secure communication
	Signature            *Signature `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AutoRefRegistration) Reset()         { *m = AutoRefRegistration{} }
func (m *AutoRefRegistration) String() string { return proto.CompactTextString(m) }
func (*AutoRefRegistration) ProtoMessage()    {}
func (*AutoRefRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{0}
}

func (m *AutoRefRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoRefRegistration.Unmarshal(m, b)
}
func (m *AutoRefRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoRefRegistration.Marshal(b, m, deterministic)
}
func (m *AutoRefRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoRefRegistration.Merge(m, src)
}
func (m *AutoRefRegistration) XXX_Size() int {
	return xxx_messageInfo_AutoRefRegistration.Size(m)
}
func (m *AutoRefRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoRefRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_AutoRefRegistration proto.InternalMessageInfo

func (m *AutoRefRegistration) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *AutoRefRegistration) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// AutoRefToController is the wrapper message for all subsequent messages from the autoRef to the controller
type AutoRefToController struct {
	// signature can optionally be specified to enable secure communication
	Signature *Signature `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	// game_event is an optional event that the autoRef detected during the game
	GameEvent *state.GameEvent `protobuf:"bytes,2,opt,name=game_event,json=gameEvent" json:"game_event,omitempty"`
	// metadata on the current game state
	GameStateMetadata    *GameStateMetadata `protobuf:"bytes,5,opt,name=game_state_metadata,json=gameStateMetadata" json:"game_state_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AutoRefToController) Reset()         { *m = AutoRefToController{} }
func (m *AutoRefToController) String() string { return proto.CompactTextString(m) }
func (*AutoRefToController) ProtoMessage()    {}
func (*AutoRefToController) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{1}
}

func (m *AutoRefToController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoRefToController.Unmarshal(m, b)
}
func (m *AutoRefToController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoRefToController.Marshal(b, m, deterministic)
}
func (m *AutoRefToController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoRefToController.Merge(m, src)
}
func (m *AutoRefToController) XXX_Size() int {
	return xxx_messageInfo_AutoRefToController.Size(m)
}
func (m *AutoRefToController) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoRefToController.DiscardUnknown(m)
}

var xxx_messageInfo_AutoRefToController proto.InternalMessageInfo

func (m *AutoRefToController) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *AutoRefToController) GetGameEvent() *state.GameEvent {
	if m != nil {
		return m.GameEvent
	}
	return nil
}

func (m *AutoRefToController) GetGameStateMetadata() *GameStateMetadata {
	if m != nil {
		return m.GameStateMetadata
	}
	return nil
}

type GameStateMetadata struct {
	// if current state is prepare_kickoff, prepare_penalty, stop or ball_placement:
	// true: all conditions are met to continue from the current state
	// false: at least one condition not met yet
	// not present: not supported by the autoRef
	// else:
	// undefined
	ReadyToContinue *bool `protobuf:"varint,1,opt,name=ready_to_continue,json=readyToContinue" json:"ready_to_continue,omitempty"`
	// if current state is stop:
	// true: ball placement not required, can directly continue
	// false: need to initiate ball placement
	// if current state is ball placement:
	// true: ball placement done, all conditions met
	// false: ball not yet placed successfully
	BallPlaced *bool `protobuf:"varint,2,opt,name=ball_placed,json=ballPlaced" json:"ball_placed,omitempty"`
	// UNIX timestamp [μs] when the ball last moved
	// Used by the GC to determine if there is still progress
	LastProgress *uint64 `protobuf:"varint,3,opt,name=last_progress,json=lastProgress" json:"last_progress,omitempty"`
	// number of yellow robots currently visible on the field
	NumberOfRobotsYellow *uint32 `protobuf:"varint,4,opt,name=number_of_robots_yellow,json=numberOfRobotsYellow" json:"number_of_robots_yellow,omitempty"`
	// number of blue robots currently visible on the field
	NumberOfRobotsBlue   *uint32  `protobuf:"varint,5,opt,name=number_of_robots_blue,json=numberOfRobotsBlue" json:"number_of_robots_blue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStateMetadata) Reset()         { *m = GameStateMetadata{} }
func (m *GameStateMetadata) String() string { return proto.CompactTextString(m) }
func (*GameStateMetadata) ProtoMessage()    {}
func (*GameStateMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{2}
}

func (m *GameStateMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStateMetadata.Unmarshal(m, b)
}
func (m *GameStateMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStateMetadata.Marshal(b, m, deterministic)
}
func (m *GameStateMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStateMetadata.Merge(m, src)
}
func (m *GameStateMetadata) XXX_Size() int {
	return xxx_messageInfo_GameStateMetadata.Size(m)
}
func (m *GameStateMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStateMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_GameStateMetadata proto.InternalMessageInfo

func (m *GameStateMetadata) GetReadyToContinue() bool {
	if m != nil && m.ReadyToContinue != nil {
		return *m.ReadyToContinue
	}
	return false
}

func (m *GameStateMetadata) GetBallPlaced() bool {
	if m != nil && m.BallPlaced != nil {
		return *m.BallPlaced
	}
	return false
}

func (m *GameStateMetadata) GetLastProgress() uint64 {
	if m != nil && m.LastProgress != nil {
		return *m.LastProgress
	}
	return 0
}

func (m *GameStateMetadata) GetNumberOfRobotsYellow() uint32 {
	if m != nil && m.NumberOfRobotsYellow != nil {
		return *m.NumberOfRobotsYellow
	}
	return 0
}

func (m *GameStateMetadata) GetNumberOfRobotsBlue() uint32 {
	if m != nil && m.NumberOfRobotsBlue != nil {
		return *m.NumberOfRobotsBlue
	}
	return 0
}

// ControllerToAutoRef is the wrapper message for all messages from controller to autoRef
type ControllerToAutoRef struct {
	// Types that are valid to be assigned to Msg:
	//	*ControllerToAutoRef_ControllerReply
	Msg                  isControllerToAutoRef_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ControllerToAutoRef) Reset()         { *m = ControllerToAutoRef{} }
func (m *ControllerToAutoRef) String() string { return proto.CompactTextString(m) }
func (*ControllerToAutoRef) ProtoMessage()    {}
func (*ControllerToAutoRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{3}
}

func (m *ControllerToAutoRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerToAutoRef.Unmarshal(m, b)
}
func (m *ControllerToAutoRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerToAutoRef.Marshal(b, m, deterministic)
}
func (m *ControllerToAutoRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerToAutoRef.Merge(m, src)
}
func (m *ControllerToAutoRef) XXX_Size() int {
	return xxx_messageInfo_ControllerToAutoRef.Size(m)
}
func (m *ControllerToAutoRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerToAutoRef.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerToAutoRef proto.InternalMessageInfo

type isControllerToAutoRef_Msg interface {
	isControllerToAutoRef_Msg()
}

type ControllerToAutoRef_ControllerReply struct {
	ControllerReply *ControllerReply `protobuf:"bytes,1,opt,name=controller_reply,json=controllerReply,oneof"`
}

func (*ControllerToAutoRef_ControllerReply) isControllerToAutoRef_Msg() {}

func (m *ControllerToAutoRef) GetMsg() isControllerToAutoRef_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ControllerToAutoRef) GetControllerReply() *ControllerReply {
	if x, ok := m.GetMsg().(*ControllerToAutoRef_ControllerReply); ok {
		return x.ControllerReply
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ControllerToAutoRef) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ControllerToAutoRef_ControllerReply)(nil),
	}
}

func init() {
	proto.RegisterType((*AutoRefRegistration)(nil), "AutoRefRegistration")
	proto.RegisterType((*AutoRefToController)(nil), "AutoRefToController")
	proto.RegisterType((*GameStateMetadata)(nil), "GameStateMetadata")
	proto.RegisterType((*ControllerToAutoRef)(nil), "ControllerToAutoRef")
}

func init() {
	proto.RegisterFile("ssl_game_controller_auto_ref.proto", fileDescriptor_2fbb3ba3bab9727c)
}

var fileDescriptor_2fbb3ba3bab9727c = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x51, 0x8b, 0xd3, 0x40,
	0x14, 0x85, 0xcd, 0x36, 0x85, 0x76, 0xd6, 0xb2, 0xed, 0x74, 0xc5, 0xe0, 0x83, 0x86, 0xf8, 0x12,
	0x85, 0x36, 0x28, 0xf8, 0xa6, 0x82, 0x5d, 0x44, 0x59, 0x14, 0x97, 0xe9, 0xbe, 0xa8, 0x0f, 0xc3,
	0x24, 0xbd, 0x89, 0x81, 0xc9, 0xdc, 0x30, 0x33, 0x51, 0xfa, 0xd7, 0xfc, 0x53, 0xfe, 0x05, 0xc9,
	0x34, 0xdb, 0x6c, 0xad, 0xec, 0x5b, 0xf8, 0xce, 0x39, 0x73, 0xe7, 0xce, 0x09, 0x89, 0x8c, 0x91,
	0xbc, 0x10, 0x15, 0xf0, 0x0c, 0x95, 0xd5, 0x28, 0x25, 0x68, 0x2e, 0x1a, 0x8b, 0x5c, 0x43, 0xbe,
	0xac, 0x35, 0x5a, 0x7c, 0x74, 0xbe, 0xf7, 0xc0, 0x4f, 0x50, 0xb6, 0xa3, 0xe1, 0xff, 0x92, 0x19,
	0x56, 0x15, 0xaa, 0x9d, 0x23, 0xe2, 0x64, 0xfe, 0xae, 0xb1, 0xc8, 0x20, 0x67, 0x50, 0x94, 0xc6,
	0x6a, 0x61, 0x4b, 0x54, 0xf4, 0x31, 0x21, 0xe5, 0x06, 0x94, 0x2d, 0xf3, 0x12, 0x74, 0xe0, 0x85,
	0x27, 0xf1, 0x98, 0xdd, 0x22, 0x34, 0x26, 0x63, 0x53, 0x16, 0x4a, 0xd8, 0x46, 0x43, 0x70, 0x12,
	0x7a, 0xf1, 0xe9, 0x4b, 0xb2, 0x5c, 0xdf, 0x10, 0xd6, 0x8b, 0xd1, 0x6f, 0x6f, 0x3f, 0xe1, 0x1a,
	0x2f, 0xf6, 0xb7, 0x38, 0x3c, 0xc1, 0xbb, 0xe3, 0x04, 0xfa, 0x8c, 0x90, 0x7e, 0xb1, 0xfd, 0xb0,
	0x0f, 0xa2, 0x82, 0xf7, 0x2d, 0x61, 0xe3, 0xe2, 0xe6, 0x93, 0xae, 0xc8, 0xdc, 0x59, 0x8d, 0x15,
	0x16, 0x78, 0x05, 0x56, 0x6c, 0x84, 0x15, 0xc1, 0xd0, 0x65, 0xa8, 0xcb, 0xac, 0x5b, 0xe9, 0x73,
	0xa7, 0xb0, 0x59, 0xf1, 0x2f, 0xba, 0xf4, 0x47, 0x83, 0xa9, 0x7f, 0xe9, 0x8f, 0xfc, 0xe9, 0x30,
	0xfa, 0xe3, 0x91, 0xd9, 0x51, 0x88, 0x3e, 0x27, 0x33, 0x0d, 0x62, 0xb3, 0xe5, 0x16, 0xdd, 0xbb,
	0x96, 0xaa, 0xd9, 0xad, 0x30, 0x62, 0x67, 0x4e, 0xd8, 0x2d, 0xda, 0x62, 0xfa, 0x84, 0x9c, 0xa6,
	0x42, 0x4a, 0x5e, 0x4b, 0x91, 0xc1, 0xc6, 0xdd, 0x7e, 0xc4, 0x48, 0x8b, 0xae, 0x1c, 0xa1, 0x4f,
	0xc9, 0x44, 0x0a, 0x63, 0x79, 0xad, 0xb1, 0xd0, 0x60, 0x4c, 0x30, 0x08, 0xbd, 0xd8, 0x67, 0xf7,
	0x5b, 0x78, 0xd5, 0x31, 0xfa, 0x8a, 0x3c, 0x54, 0x4d, 0x95, 0x82, 0xe6, 0x98, 0x73, 0x8d, 0x29,
	0x5a, 0xc3, 0xb7, 0x20, 0x25, 0xfe, 0x0a, 0xfc, 0xd0, 0x8b, 0x27, 0xec, 0x7c, 0x27, 0x7f, 0xc9,
	0x99, 0x13, 0xbf, 0x3a, 0x8d, 0xbe, 0x20, 0x0f, 0x8e, 0x62, 0xa9, 0x6c, 0xc0, 0x3d, 0xc8, 0x84,
	0xd1, 0xc3, 0xd0, 0x4a, 0x36, 0x10, 0x7d, 0x27, 0xf3, 0xbe, 0xa4, 0x6b, 0xec, 0x9a, 0xa3, 0x6f,
	0xc8, 0xf4, 0xd6, 0x1f, 0xa4, 0xa1, 0x96, 0xdb, 0xae, 0xb4, 0xe9, 0xb2, 0xf7, 0xb3, 0x96, 0x7f,
	0xbc, 0xc7, 0xce, 0xb2, 0x43, 0xb4, 0x1a, 0x92, 0x41, 0x65, 0x8a, 0xd5, 0xdb, 0x6f, 0xaf, 0x8b,
	0xd2, 0xfe, 0x68, 0xd2, 0x65, 0x86, 0x55, 0xd2, 0x4e, 0xbd, 0x68, 0xea, 0xc5, 0x7a, 0xfd, 0x29,
	0x31, 0x46, 0x2e, 0xda, 0x2a, 0x16, 0x7d, 0x32, 0x29, 0x95, 0x05, 0xad, 0x84, 0x4c, 0x44, 0x5d,
	0x27, 0x3a, 0x43, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xef, 0x66, 0xeb, 0x09, 0x03, 0x00,
	0x00,
}
