// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_gc_change.proto

package statemachine

import (
	fmt "fmt"
	geom "github.com/RoboCup-SSL/ssl-game-controller/internal/app/geom"
	state "github.com/RoboCup-SSL/ssl-game-controller/internal/app/state"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateChange struct {
	Id                   *int32               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	StatePre             *state.State         `protobuf:"bytes,2,opt,name=state_pre,json=statePre" json:"state_pre,omitempty"`
	State                *state.State         `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Change               *Change              `protobuf:"bytes,4,opt,name=change" json:"change,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StateChange) Reset()         { *m = StateChange{} }
func (m *StateChange) String() string { return proto.CompactTextString(m) }
func (*StateChange) ProtoMessage()    {}
func (*StateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{0}
}

func (m *StateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChange.Unmarshal(m, b)
}
func (m *StateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChange.Marshal(b, m, deterministic)
}
func (m *StateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChange.Merge(m, src)
}
func (m *StateChange) XXX_Size() int {
	return xxx_messageInfo_StateChange.Size(m)
}
func (m *StateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChange.DiscardUnknown(m)
}

var xxx_messageInfo_StateChange proto.InternalMessageInfo

func (m *StateChange) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *StateChange) GetStatePre() *state.State {
	if m != nil {
		return m.StatePre
	}
	return nil
}

func (m *StateChange) GetState() *state.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *StateChange) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

func (m *StateChange) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Change struct {
	Origin     *string `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Revertible *bool   `protobuf:"varint,16,opt,name=revertible" json:"revertible,omitempty"`
	// Types that are valid to be assigned to Change:
	//	*Change_NewCommand
	//	*Change_ChangeStage
	//	*Change_SetBallPlacementPos
	//	*Change_AddYellowCard
	//	*Change_AddRedCard
	//	*Change_YellowCardOver
	//	*Change_AddGameEvent
	//	*Change_AddProposedGameEvent
	//	*Change_StartBallPlacement
	//	*Change_Continue
	//	*Change_UpdateConfig
	//	*Change_UpdateTeamState
	//	*Change_SwitchColors
	//	*Change_Revert
	//	*Change_NewGameState
	//	*Change_AcceptGameEventProposals
	Change               isChange_Change `protobuf_oneof:"change"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{1}
}

func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetOrigin() string {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return ""
}

func (m *Change) GetRevertible() bool {
	if m != nil && m.Revertible != nil {
		return *m.Revertible
	}
	return false
}

type isChange_Change interface {
	isChange_Change()
}

type Change_NewCommand struct {
	NewCommand *NewCommand `protobuf:"bytes,2,opt,name=new_command,json=newCommand,oneof"`
}

type Change_ChangeStage struct {
	ChangeStage *ChangeStage `protobuf:"bytes,3,opt,name=change_stage,json=changeStage,oneof"`
}

type Change_SetBallPlacementPos struct {
	SetBallPlacementPos *SetBallPlacementPos `protobuf:"bytes,4,opt,name=set_ball_placement_pos,json=setBallPlacementPos,oneof"`
}

type Change_AddYellowCard struct {
	AddYellowCard *AddYellowCard `protobuf:"bytes,5,opt,name=add_yellow_card,json=addYellowCard,oneof"`
}

type Change_AddRedCard struct {
	AddRedCard *AddRedCard `protobuf:"bytes,6,opt,name=add_red_card,json=addRedCard,oneof"`
}

type Change_YellowCardOver struct {
	YellowCardOver *YellowCardOver `protobuf:"bytes,7,opt,name=yellow_card_over,json=yellowCardOver,oneof"`
}

type Change_AddGameEvent struct {
	AddGameEvent *AddGameEvent `protobuf:"bytes,8,opt,name=add_game_event,json=addGameEvent,oneof"`
}

type Change_AddProposedGameEvent struct {
	AddProposedGameEvent *AddProposedGameEvent `protobuf:"bytes,9,opt,name=add_proposed_game_event,json=addProposedGameEvent,oneof"`
}

type Change_StartBallPlacement struct {
	StartBallPlacement *StartBallPlacement `protobuf:"bytes,10,opt,name=start_ball_placement,json=startBallPlacement,oneof"`
}

type Change_Continue struct {
	Continue *Continue `protobuf:"bytes,11,opt,name=continue,oneof"`
}

type Change_UpdateConfig struct {
	UpdateConfig *UpdateConfig `protobuf:"bytes,12,opt,name=update_config,json=updateConfig,oneof"`
}

type Change_UpdateTeamState struct {
	UpdateTeamState *UpdateTeamState `protobuf:"bytes,13,opt,name=update_team_state,json=updateTeamState,oneof"`
}

type Change_SwitchColors struct {
	SwitchColors *SwitchColors `protobuf:"bytes,14,opt,name=switch_colors,json=switchColors,oneof"`
}

type Change_Revert struct {
	Revert *Revert `protobuf:"bytes,15,opt,name=revert,oneof"`
}

type Change_NewGameState struct {
	NewGameState *NewGameState `protobuf:"bytes,17,opt,name=new_game_state,json=newGameState,oneof"`
}

type Change_AcceptGameEventProposals struct {
	AcceptGameEventProposals *AcceptGameEventProposals `protobuf:"bytes,18,opt,name=accept_game_event_proposals,json=acceptGameEventProposals,oneof"`
}

func (*Change_NewCommand) isChange_Change() {}

func (*Change_ChangeStage) isChange_Change() {}

func (*Change_SetBallPlacementPos) isChange_Change() {}

func (*Change_AddYellowCard) isChange_Change() {}

func (*Change_AddRedCard) isChange_Change() {}

func (*Change_YellowCardOver) isChange_Change() {}

func (*Change_AddGameEvent) isChange_Change() {}

func (*Change_AddProposedGameEvent) isChange_Change() {}

func (*Change_StartBallPlacement) isChange_Change() {}

func (*Change_Continue) isChange_Change() {}

func (*Change_UpdateConfig) isChange_Change() {}

func (*Change_UpdateTeamState) isChange_Change() {}

func (*Change_SwitchColors) isChange_Change() {}

func (*Change_Revert) isChange_Change() {}

func (*Change_NewGameState) isChange_Change() {}

func (*Change_AcceptGameEventProposals) isChange_Change() {}

func (m *Change) GetChange() isChange_Change {
	if m != nil {
		return m.Change
	}
	return nil
}

func (m *Change) GetNewCommand() *NewCommand {
	if x, ok := m.GetChange().(*Change_NewCommand); ok {
		return x.NewCommand
	}
	return nil
}

func (m *Change) GetChangeStage() *ChangeStage {
	if x, ok := m.GetChange().(*Change_ChangeStage); ok {
		return x.ChangeStage
	}
	return nil
}

func (m *Change) GetSetBallPlacementPos() *SetBallPlacementPos {
	if x, ok := m.GetChange().(*Change_SetBallPlacementPos); ok {
		return x.SetBallPlacementPos
	}
	return nil
}

func (m *Change) GetAddYellowCard() *AddYellowCard {
	if x, ok := m.GetChange().(*Change_AddYellowCard); ok {
		return x.AddYellowCard
	}
	return nil
}

func (m *Change) GetAddRedCard() *AddRedCard {
	if x, ok := m.GetChange().(*Change_AddRedCard); ok {
		return x.AddRedCard
	}
	return nil
}

func (m *Change) GetYellowCardOver() *YellowCardOver {
	if x, ok := m.GetChange().(*Change_YellowCardOver); ok {
		return x.YellowCardOver
	}
	return nil
}

func (m *Change) GetAddGameEvent() *AddGameEvent {
	if x, ok := m.GetChange().(*Change_AddGameEvent); ok {
		return x.AddGameEvent
	}
	return nil
}

func (m *Change) GetAddProposedGameEvent() *AddProposedGameEvent {
	if x, ok := m.GetChange().(*Change_AddProposedGameEvent); ok {
		return x.AddProposedGameEvent
	}
	return nil
}

func (m *Change) GetStartBallPlacement() *StartBallPlacement {
	if x, ok := m.GetChange().(*Change_StartBallPlacement); ok {
		return x.StartBallPlacement
	}
	return nil
}

func (m *Change) GetContinue() *Continue {
	if x, ok := m.GetChange().(*Change_Continue); ok {
		return x.Continue
	}
	return nil
}

func (m *Change) GetUpdateConfig() *UpdateConfig {
	if x, ok := m.GetChange().(*Change_UpdateConfig); ok {
		return x.UpdateConfig
	}
	return nil
}

func (m *Change) GetUpdateTeamState() *UpdateTeamState {
	if x, ok := m.GetChange().(*Change_UpdateTeamState); ok {
		return x.UpdateTeamState
	}
	return nil
}

func (m *Change) GetSwitchColors() *SwitchColors {
	if x, ok := m.GetChange().(*Change_SwitchColors); ok {
		return x.SwitchColors
	}
	return nil
}

func (m *Change) GetRevert() *Revert {
	if x, ok := m.GetChange().(*Change_Revert); ok {
		return x.Revert
	}
	return nil
}

func (m *Change) GetNewGameState() *NewGameState {
	if x, ok := m.GetChange().(*Change_NewGameState); ok {
		return x.NewGameState
	}
	return nil
}

func (m *Change) GetAcceptGameEventProposals() *AcceptGameEventProposals {
	if x, ok := m.GetChange().(*Change_AcceptGameEventProposals); ok {
		return x.AcceptGameEventProposals
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Change) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Change_NewCommand)(nil),
		(*Change_ChangeStage)(nil),
		(*Change_SetBallPlacementPos)(nil),
		(*Change_AddYellowCard)(nil),
		(*Change_AddRedCard)(nil),
		(*Change_YellowCardOver)(nil),
		(*Change_AddGameEvent)(nil),
		(*Change_AddProposedGameEvent)(nil),
		(*Change_StartBallPlacement)(nil),
		(*Change_Continue)(nil),
		(*Change_UpdateConfig)(nil),
		(*Change_UpdateTeamState)(nil),
		(*Change_SwitchColors)(nil),
		(*Change_Revert)(nil),
		(*Change_NewGameState)(nil),
		(*Change_AcceptGameEventProposals)(nil),
	}
}

type NewCommand struct {
	Command              *state.Command `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NewCommand) Reset()         { *m = NewCommand{} }
func (m *NewCommand) String() string { return proto.CompactTextString(m) }
func (*NewCommand) ProtoMessage()    {}
func (*NewCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{2}
}

func (m *NewCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCommand.Unmarshal(m, b)
}
func (m *NewCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCommand.Marshal(b, m, deterministic)
}
func (m *NewCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCommand.Merge(m, src)
}
func (m *NewCommand) XXX_Size() int {
	return xxx_messageInfo_NewCommand.Size(m)
}
func (m *NewCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCommand.DiscardUnknown(m)
}

var xxx_messageInfo_NewCommand proto.InternalMessageInfo

func (m *NewCommand) GetCommand() *state.Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type ChangeStage struct {
	NewStage             *state.Referee_Stage `protobuf:"varint,1,opt,name=new_stage,json=newStage,enum=Referee_Stage" json:"new_stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChangeStage) Reset()         { *m = ChangeStage{} }
func (m *ChangeStage) String() string { return proto.CompactTextString(m) }
func (*ChangeStage) ProtoMessage()    {}
func (*ChangeStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{3}
}

func (m *ChangeStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStage.Unmarshal(m, b)
}
func (m *ChangeStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStage.Marshal(b, m, deterministic)
}
func (m *ChangeStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStage.Merge(m, src)
}
func (m *ChangeStage) XXX_Size() int {
	return xxx_messageInfo_ChangeStage.Size(m)
}
func (m *ChangeStage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStage.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStage proto.InternalMessageInfo

func (m *ChangeStage) GetNewStage() state.Referee_Stage {
	if m != nil && m.NewStage != nil {
		return *m.NewStage
	}
	return state.Referee_NORMAL_FIRST_HALF_PRE
}

type SetBallPlacementPos struct {
	Pos                  *geom.Vector2 `protobuf:"bytes,1,opt,name=pos" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetBallPlacementPos) Reset()         { *m = SetBallPlacementPos{} }
func (m *SetBallPlacementPos) String() string { return proto.CompactTextString(m) }
func (*SetBallPlacementPos) ProtoMessage()    {}
func (*SetBallPlacementPos) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{4}
}

func (m *SetBallPlacementPos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBallPlacementPos.Unmarshal(m, b)
}
func (m *SetBallPlacementPos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBallPlacementPos.Marshal(b, m, deterministic)
}
func (m *SetBallPlacementPos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBallPlacementPos.Merge(m, src)
}
func (m *SetBallPlacementPos) XXX_Size() int {
	return xxx_messageInfo_SetBallPlacementPos.Size(m)
}
func (m *SetBallPlacementPos) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBallPlacementPos.DiscardUnknown(m)
}

var xxx_messageInfo_SetBallPlacementPos proto.InternalMessageInfo

func (m *SetBallPlacementPos) GetPos() *geom.Vector2 {
	if m != nil {
		return m.Pos
	}
	return nil
}

type AddYellowCard struct {
	ForTeam              *state.Team      `protobuf:"varint,1,opt,name=for_team,json=forTeam,enum=Team" json:"for_team,omitempty"`
	CausedByGameEvent    *state.GameEvent `protobuf:"bytes,2,opt,name=caused_by_game_event,json=causedByGameEvent" json:"caused_by_game_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddYellowCard) Reset()         { *m = AddYellowCard{} }
func (m *AddYellowCard) String() string { return proto.CompactTextString(m) }
func (*AddYellowCard) ProtoMessage()    {}
func (*AddYellowCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{5}
}

func (m *AddYellowCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddYellowCard.Unmarshal(m, b)
}
func (m *AddYellowCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddYellowCard.Marshal(b, m, deterministic)
}
func (m *AddYellowCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddYellowCard.Merge(m, src)
}
func (m *AddYellowCard) XXX_Size() int {
	return xxx_messageInfo_AddYellowCard.Size(m)
}
func (m *AddYellowCard) XXX_DiscardUnknown() {
	xxx_messageInfo_AddYellowCard.DiscardUnknown(m)
}

var xxx_messageInfo_AddYellowCard proto.InternalMessageInfo

func (m *AddYellowCard) GetForTeam() state.Team {
	if m != nil && m.ForTeam != nil {
		return *m.ForTeam
	}
	return state.Team_UNKNOWN
}

func (m *AddYellowCard) GetCausedByGameEvent() *state.GameEvent {
	if m != nil {
		return m.CausedByGameEvent
	}
	return nil
}

type AddRedCard struct {
	ForTeam              *state.Team      `protobuf:"varint,1,opt,name=for_team,json=forTeam,enum=Team" json:"for_team,omitempty"`
	CausedByGameEvent    *state.GameEvent `protobuf:"bytes,2,opt,name=caused_by_game_event,json=causedByGameEvent" json:"caused_by_game_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddRedCard) Reset()         { *m = AddRedCard{} }
func (m *AddRedCard) String() string { return proto.CompactTextString(m) }
func (*AddRedCard) ProtoMessage()    {}
func (*AddRedCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{6}
}

func (m *AddRedCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRedCard.Unmarshal(m, b)
}
func (m *AddRedCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRedCard.Marshal(b, m, deterministic)
}
func (m *AddRedCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRedCard.Merge(m, src)
}
func (m *AddRedCard) XXX_Size() int {
	return xxx_messageInfo_AddRedCard.Size(m)
}
func (m *AddRedCard) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRedCard.DiscardUnknown(m)
}

var xxx_messageInfo_AddRedCard proto.InternalMessageInfo

func (m *AddRedCard) GetForTeam() state.Team {
	if m != nil && m.ForTeam != nil {
		return *m.ForTeam
	}
	return state.Team_UNKNOWN
}

func (m *AddRedCard) GetCausedByGameEvent() *state.GameEvent {
	if m != nil {
		return m.CausedByGameEvent
	}
	return nil
}

type YellowCardOver struct {
	ForTeam              *state.Team `protobuf:"varint,1,opt,name=for_team,json=forTeam,enum=Team" json:"for_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *YellowCardOver) Reset()         { *m = YellowCardOver{} }
func (m *YellowCardOver) String() string { return proto.CompactTextString(m) }
func (*YellowCardOver) ProtoMessage()    {}
func (*YellowCardOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{7}
}

func (m *YellowCardOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YellowCardOver.Unmarshal(m, b)
}
func (m *YellowCardOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YellowCardOver.Marshal(b, m, deterministic)
}
func (m *YellowCardOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YellowCardOver.Merge(m, src)
}
func (m *YellowCardOver) XXX_Size() int {
	return xxx_messageInfo_YellowCardOver.Size(m)
}
func (m *YellowCardOver) XXX_DiscardUnknown() {
	xxx_messageInfo_YellowCardOver.DiscardUnknown(m)
}

var xxx_messageInfo_YellowCardOver proto.InternalMessageInfo

func (m *YellowCardOver) GetForTeam() state.Team {
	if m != nil && m.ForTeam != nil {
		return *m.ForTeam
	}
	return state.Team_UNKNOWN
}

type AddGameEvent struct {
	GameEvent            *state.GameEvent `protobuf:"bytes,1,opt,name=game_event,json=gameEvent" json:"game_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddGameEvent) Reset()         { *m = AddGameEvent{} }
func (m *AddGameEvent) String() string { return proto.CompactTextString(m) }
func (*AddGameEvent) ProtoMessage()    {}
func (*AddGameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{8}
}

func (m *AddGameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGameEvent.Unmarshal(m, b)
}
func (m *AddGameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGameEvent.Marshal(b, m, deterministic)
}
func (m *AddGameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGameEvent.Merge(m, src)
}
func (m *AddGameEvent) XXX_Size() int {
	return xxx_messageInfo_AddGameEvent.Size(m)
}
func (m *AddGameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AddGameEvent proto.InternalMessageInfo

func (m *AddGameEvent) GetGameEvent() *state.GameEvent {
	if m != nil {
		return m.GameEvent
	}
	return nil
}

type AddProposedGameEvent struct {
	Proposal             *state.GameEventProposal `protobuf:"bytes,1,opt,name=proposal" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AddProposedGameEvent) Reset()         { *m = AddProposedGameEvent{} }
func (m *AddProposedGameEvent) String() string { return proto.CompactTextString(m) }
func (*AddProposedGameEvent) ProtoMessage()    {}
func (*AddProposedGameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{9}
}

func (m *AddProposedGameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProposedGameEvent.Unmarshal(m, b)
}
func (m *AddProposedGameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProposedGameEvent.Marshal(b, m, deterministic)
}
func (m *AddProposedGameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProposedGameEvent.Merge(m, src)
}
func (m *AddProposedGameEvent) XXX_Size() int {
	return xxx_messageInfo_AddProposedGameEvent.Size(m)
}
func (m *AddProposedGameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProposedGameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AddProposedGameEvent proto.InternalMessageInfo

func (m *AddProposedGameEvent) GetProposal() *state.GameEventProposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

type AcceptGameEventProposals struct {
	Proposals            []*state.GameEventProposal `protobuf:"bytes,1,rep,name=proposals" json:"proposals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AcceptGameEventProposals) Reset()         { *m = AcceptGameEventProposals{} }
func (m *AcceptGameEventProposals) String() string { return proto.CompactTextString(m) }
func (*AcceptGameEventProposals) ProtoMessage()    {}
func (*AcceptGameEventProposals) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{10}
}

func (m *AcceptGameEventProposals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptGameEventProposals.Unmarshal(m, b)
}
func (m *AcceptGameEventProposals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptGameEventProposals.Marshal(b, m, deterministic)
}
func (m *AcceptGameEventProposals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptGameEventProposals.Merge(m, src)
}
func (m *AcceptGameEventProposals) XXX_Size() int {
	return xxx_messageInfo_AcceptGameEventProposals.Size(m)
}
func (m *AcceptGameEventProposals) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptGameEventProposals.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptGameEventProposals proto.InternalMessageInfo

func (m *AcceptGameEventProposals) GetProposals() []*state.GameEventProposal {
	if m != nil {
		return m.Proposals
	}
	return nil
}

type StartBallPlacement struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartBallPlacement) Reset()         { *m = StartBallPlacement{} }
func (m *StartBallPlacement) String() string { return proto.CompactTextString(m) }
func (*StartBallPlacement) ProtoMessage()    {}
func (*StartBallPlacement) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{11}
}

func (m *StartBallPlacement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartBallPlacement.Unmarshal(m, b)
}
func (m *StartBallPlacement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartBallPlacement.Marshal(b, m, deterministic)
}
func (m *StartBallPlacement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartBallPlacement.Merge(m, src)
}
func (m *StartBallPlacement) XXX_Size() int {
	return xxx_messageInfo_StartBallPlacement.Size(m)
}
func (m *StartBallPlacement) XXX_DiscardUnknown() {
	xxx_messageInfo_StartBallPlacement.DiscardUnknown(m)
}

var xxx_messageInfo_StartBallPlacement proto.InternalMessageInfo

type Continue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Continue) Reset()         { *m = Continue{} }
func (m *Continue) String() string { return proto.CompactTextString(m) }
func (*Continue) ProtoMessage()    {}
func (*Continue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{12}
}

func (m *Continue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Continue.Unmarshal(m, b)
}
func (m *Continue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Continue.Marshal(b, m, deterministic)
}
func (m *Continue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Continue.Merge(m, src)
}
func (m *Continue) XXX_Size() int {
	return xxx_messageInfo_Continue.Size(m)
}
func (m *Continue) XXX_DiscardUnknown() {
	xxx_messageInfo_Continue.DiscardUnknown(m)
}

var xxx_messageInfo_Continue proto.InternalMessageInfo

type UpdateConfig struct {
	Division             *state.Division `protobuf:"varint,1,opt,name=division,enum=Division" json:"division,omitempty"`
	FirstKickoffTeam     *state.Team     `protobuf:"varint,2,opt,name=first_kickoff_team,json=firstKickoffTeam,enum=Team" json:"first_kickoff_team,omitempty"`
	AutoContinue         *bool           `protobuf:"varint,3,opt,name=auto_continue,json=autoContinue" json:"auto_continue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateConfig) Reset()         { *m = UpdateConfig{} }
func (m *UpdateConfig) String() string { return proto.CompactTextString(m) }
func (*UpdateConfig) ProtoMessage()    {}
func (*UpdateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{13}
}

func (m *UpdateConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfig.Unmarshal(m, b)
}
func (m *UpdateConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfig.Marshal(b, m, deterministic)
}
func (m *UpdateConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfig.Merge(m, src)
}
func (m *UpdateConfig) XXX_Size() int {
	return xxx_messageInfo_UpdateConfig.Size(m)
}
func (m *UpdateConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfig.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfig proto.InternalMessageInfo

func (m *UpdateConfig) GetDivision() state.Division {
	if m != nil && m.Division != nil {
		return *m.Division
	}
	return state.Division_DIV_UNKNOWN
}

func (m *UpdateConfig) GetFirstKickoffTeam() state.Team {
	if m != nil && m.FirstKickoffTeam != nil {
		return *m.FirstKickoffTeam
	}
	return state.Team_UNKNOWN
}

func (m *UpdateConfig) GetAutoContinue() bool {
	if m != nil && m.AutoContinue != nil {
		return *m.AutoContinue
	}
	return false
}

type UpdateTeamState struct {
	ForTeam               *state.Team       `protobuf:"varint,1,opt,name=for_team,json=forTeam,enum=Team" json:"for_team,omitempty"`
	TeamName              *string           `protobuf:"bytes,2,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	Goals                 *int32            `protobuf:"varint,3,opt,name=goals" json:"goals,omitempty"`
	Goalkeeper            *int32            `protobuf:"varint,4,opt,name=goalkeeper" json:"goalkeeper,omitempty"`
	TimeoutsLeft          *int32            `protobuf:"varint,5,opt,name=timeouts_left,json=timeoutsLeft" json:"timeouts_left,omitempty"`
	TimeoutTimeLeft       *string           `protobuf:"bytes,6,opt,name=timeout_time_left,json=timeoutTimeLeft" json:"timeout_time_left,omitempty"`
	OnPositiveHalf        *bool             `protobuf:"varint,7,opt,name=on_positive_half,json=onPositiveHalf" json:"on_positive_half,omitempty"`
	BallPlacementFailures *int32            `protobuf:"varint,8,opt,name=ball_placement_failures,json=ballPlacementFailures" json:"ball_placement_failures,omitempty"`
	CanPlaceBall          *bool             `protobuf:"varint,9,opt,name=can_place_ball,json=canPlaceBall" json:"can_place_ball,omitempty"`
	BotSubstitutionIntent *bool             `protobuf:"varint,10,opt,name=bot_substitution_intent,json=botSubstitutionIntent" json:"bot_substitution_intent,omitempty"`
	YellowCard            *state.YellowCard `protobuf:"bytes,11,opt,name=yellow_card,json=yellowCard" json:"yellow_card,omitempty"`
	RedCard               *state.RedCard    `protobuf:"bytes,12,opt,name=red_card,json=redCard" json:"red_card,omitempty"`
	Foul                  *state.Foul       `protobuf:"bytes,13,opt,name=foul" json:"foul,omitempty"`
	RemoveYellowCard      *uint32           `protobuf:"varint,14,opt,name=remove_yellow_card,json=removeYellowCard" json:"remove_yellow_card,omitempty"`
	RemoveRedCard         *uint32           `protobuf:"varint,15,opt,name=remove_red_card,json=removeRedCard" json:"remove_red_card,omitempty"`
	RemoveFoul            *uint32           `protobuf:"varint,16,opt,name=remove_foul,json=removeFoul" json:"remove_foul,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *UpdateTeamState) Reset()         { *m = UpdateTeamState{} }
func (m *UpdateTeamState) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamState) ProtoMessage()    {}
func (*UpdateTeamState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{14}
}

func (m *UpdateTeamState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamState.Unmarshal(m, b)
}
func (m *UpdateTeamState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamState.Marshal(b, m, deterministic)
}
func (m *UpdateTeamState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamState.Merge(m, src)
}
func (m *UpdateTeamState) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamState.Size(m)
}
func (m *UpdateTeamState) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamState.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamState proto.InternalMessageInfo

func (m *UpdateTeamState) GetForTeam() state.Team {
	if m != nil && m.ForTeam != nil {
		return *m.ForTeam
	}
	return state.Team_UNKNOWN
}

func (m *UpdateTeamState) GetTeamName() string {
	if m != nil && m.TeamName != nil {
		return *m.TeamName
	}
	return ""
}

func (m *UpdateTeamState) GetGoals() int32 {
	if m != nil && m.Goals != nil {
		return *m.Goals
	}
	return 0
}

func (m *UpdateTeamState) GetGoalkeeper() int32 {
	if m != nil && m.Goalkeeper != nil {
		return *m.Goalkeeper
	}
	return 0
}

func (m *UpdateTeamState) GetTimeoutsLeft() int32 {
	if m != nil && m.TimeoutsLeft != nil {
		return *m.TimeoutsLeft
	}
	return 0
}

func (m *UpdateTeamState) GetTimeoutTimeLeft() string {
	if m != nil && m.TimeoutTimeLeft != nil {
		return *m.TimeoutTimeLeft
	}
	return ""
}

func (m *UpdateTeamState) GetOnPositiveHalf() bool {
	if m != nil && m.OnPositiveHalf != nil {
		return *m.OnPositiveHalf
	}
	return false
}

func (m *UpdateTeamState) GetBallPlacementFailures() int32 {
	if m != nil && m.BallPlacementFailures != nil {
		return *m.BallPlacementFailures
	}
	return 0
}

func (m *UpdateTeamState) GetCanPlaceBall() bool {
	if m != nil && m.CanPlaceBall != nil {
		return *m.CanPlaceBall
	}
	return false
}

func (m *UpdateTeamState) GetBotSubstitutionIntent() bool {
	if m != nil && m.BotSubstitutionIntent != nil {
		return *m.BotSubstitutionIntent
	}
	return false
}

func (m *UpdateTeamState) GetYellowCard() *state.YellowCard {
	if m != nil {
		return m.YellowCard
	}
	return nil
}

func (m *UpdateTeamState) GetRedCard() *state.RedCard {
	if m != nil {
		return m.RedCard
	}
	return nil
}

func (m *UpdateTeamState) GetFoul() *state.Foul {
	if m != nil {
		return m.Foul
	}
	return nil
}

func (m *UpdateTeamState) GetRemoveYellowCard() uint32 {
	if m != nil && m.RemoveYellowCard != nil {
		return *m.RemoveYellowCard
	}
	return 0
}

func (m *UpdateTeamState) GetRemoveRedCard() uint32 {
	if m != nil && m.RemoveRedCard != nil {
		return *m.RemoveRedCard
	}
	return 0
}

func (m *UpdateTeamState) GetRemoveFoul() uint32 {
	if m != nil && m.RemoveFoul != nil {
		return *m.RemoveFoul
	}
	return 0
}

type SwitchColors struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchColors) Reset()         { *m = SwitchColors{} }
func (m *SwitchColors) String() string { return proto.CompactTextString(m) }
func (*SwitchColors) ProtoMessage()    {}
func (*SwitchColors) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{15}
}

func (m *SwitchColors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchColors.Unmarshal(m, b)
}
func (m *SwitchColors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchColors.Marshal(b, m, deterministic)
}
func (m *SwitchColors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchColors.Merge(m, src)
}
func (m *SwitchColors) XXX_Size() int {
	return xxx_messageInfo_SwitchColors.Size(m)
}
func (m *SwitchColors) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchColors.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchColors proto.InternalMessageInfo

type Revert struct {
	ChangeId             *int32   `protobuf:"varint,1,opt,name=change_id,json=changeId" json:"change_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Revert) Reset()         { *m = Revert{} }
func (m *Revert) String() string { return proto.CompactTextString(m) }
func (*Revert) ProtoMessage()    {}
func (*Revert) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{16}
}

func (m *Revert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Revert.Unmarshal(m, b)
}
func (m *Revert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Revert.Marshal(b, m, deterministic)
}
func (m *Revert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Revert.Merge(m, src)
}
func (m *Revert) XXX_Size() int {
	return xxx_messageInfo_Revert.Size(m)
}
func (m *Revert) XXX_DiscardUnknown() {
	xxx_messageInfo_Revert.DiscardUnknown(m)
}

var xxx_messageInfo_Revert proto.InternalMessageInfo

func (m *Revert) GetChangeId() int32 {
	if m != nil && m.ChangeId != nil {
		return *m.ChangeId
	}
	return 0
}

type NewGameState struct {
	GameState            *state.GameState `protobuf:"bytes,1,opt,name=game_state,json=gameState" json:"game_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NewGameState) Reset()         { *m = NewGameState{} }
func (m *NewGameState) String() string { return proto.CompactTextString(m) }
func (*NewGameState) ProtoMessage()    {}
func (*NewGameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0de3f29222370fd, []int{17}
}

func (m *NewGameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameState.Unmarshal(m, b)
}
func (m *NewGameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameState.Marshal(b, m, deterministic)
}
func (m *NewGameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameState.Merge(m, src)
}
func (m *NewGameState) XXX_Size() int {
	return xxx_messageInfo_NewGameState.Size(m)
}
func (m *NewGameState) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameState.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameState proto.InternalMessageInfo

func (m *NewGameState) GetGameState() *state.GameState {
	if m != nil {
		return m.GameState
	}
	return nil
}

func init() {
	proto.RegisterType((*StateChange)(nil), "StateChange")
	proto.RegisterType((*Change)(nil), "Change")
	proto.RegisterType((*NewCommand)(nil), "NewCommand")
	proto.RegisterType((*ChangeStage)(nil), "ChangeStage")
	proto.RegisterType((*SetBallPlacementPos)(nil), "SetBallPlacementPos")
	proto.RegisterType((*AddYellowCard)(nil), "AddYellowCard")
	proto.RegisterType((*AddRedCard)(nil), "AddRedCard")
	proto.RegisterType((*YellowCardOver)(nil), "YellowCardOver")
	proto.RegisterType((*AddGameEvent)(nil), "AddGameEvent")
	proto.RegisterType((*AddProposedGameEvent)(nil), "AddProposedGameEvent")
	proto.RegisterType((*AcceptGameEventProposals)(nil), "AcceptGameEventProposals")
	proto.RegisterType((*StartBallPlacement)(nil), "StartBallPlacement")
	proto.RegisterType((*Continue)(nil), "Continue")
	proto.RegisterType((*UpdateConfig)(nil), "UpdateConfig")
	proto.RegisterType((*UpdateTeamState)(nil), "UpdateTeamState")
	proto.RegisterType((*SwitchColors)(nil), "SwitchColors")
	proto.RegisterType((*Revert)(nil), "Revert")
	proto.RegisterType((*NewGameState)(nil), "NewGameState")
}

func init() {
	proto.RegisterFile("ssl_gc_change.proto", fileDescriptor_f0de3f29222370fd)
}

var fileDescriptor_f0de3f29222370fd = []byte{
	// 1331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xeb, 0x6e, 0xdb, 0xc6,
	0x12, 0x96, 0xec, 0x48, 0xa6, 0x46, 0x57, 0xaf, 0xe5, 0x84, 0xb9, 0xe0, 0xc4, 0x87, 0x39, 0x39,
	0x75, 0xdb, 0x84, 0x4a, 0xdc, 0x0b, 0xd2, 0x06, 0x28, 0x10, 0x2b, 0x75, 0x14, 0x24, 0x70, 0x8d,
	0x55, 0x5a, 0xa0, 0xf9, 0x43, 0xac, 0xc8, 0xa5, 0x4c, 0x98, 0xe4, 0x12, 0xcb, 0xa5, 0x0c, 0x3f,
	0x45, 0x1f, 0xa8, 0xaf, 0xd6, 0x02, 0xc5, 0x5e, 0x48, 0x51, 0x71, 0x82, 0xf6, 0x4f, 0x7f, 0x91,
	0xf3, 0xcd, 0xcc, 0xce, 0xec, 0xce, 0xce, 0x7c, 0x0b, 0x7b, 0x79, 0x1e, 0x7b, 0x4b, 0xdf, 0xf3,
	0xcf, 0x49, 0xba, 0xa4, 0x6e, 0xc6, 0x99, 0x60, 0x77, 0x90, 0x01, 0x73, 0x41, 0x44, 0x89, 0x55,
	0x86, 0x2c, 0x49, 0x58, 0x6a, 0xc0, 0x7d, 0x03, 0x2e, 0x29, 0x4b, 0xa8, 0xe0, 0x57, 0x06, 0xbe,
	0x55, 0xc2, 0x24, 0xa1, 0x1e, 0x5d, 0xd1, 0x54, 0x18, 0xc5, 0x3d, 0xa3, 0xe0, 0x34, 0xa4, 0x9c,
	0x52, 0x2f, 0xa1, 0x79, 0x4e, 0xaa, 0xb0, 0xf7, 0x97, 0x8c, 0x2d, 0x63, 0x3a, 0x51, 0xd2, 0xa2,
	0x08, 0x27, 0x22, 0x4a, 0x68, 0x2e, 0x48, 0x92, 0x69, 0x03, 0xe7, 0xf7, 0x26, 0x74, 0xe7, 0x32,
	0xa7, 0xa9, 0xca, 0x16, 0x0d, 0x60, 0x2b, 0x0a, 0xec, 0xe6, 0x41, 0xf3, 0xb0, 0x85, 0xb7, 0xa2,
	0x00, 0x3d, 0x80, 0x8e, 0x4a, 0xd9, 0xcb, 0x38, 0xb5, 0xb7, 0x0e, 0x9a, 0x87, 0xdd, 0xa3, 0xb6,
	0xab, 0x1c, 0xb0, 0xa5, 0x14, 0x67, 0x9c, 0xa2, 0x7b, 0xd0, 0x52, 0xff, 0xf6, 0xf6, 0x86, 0x81,
	0x06, 0xd1, 0x7d, 0x68, 0xeb, 0xa3, 0xb0, 0x6f, 0x28, 0xf5, 0x8e, 0xab, 0x63, 0x61, 0x03, 0xa3,
	0x67, 0xd0, 0xa9, 0xd2, 0xb2, 0x5b, 0xca, 0xe6, 0x8e, 0xab, 0x13, 0x77, 0xcb, 0xc4, 0xdd, 0x77,
	0xa5, 0x05, 0x5e, 0x1b, 0x3b, 0x7f, 0xee, 0x40, 0xdb, 0x24, 0x7e, 0x13, 0xda, 0x8c, 0x47, 0xcb,
	0x28, 0x55, 0xc9, 0x77, 0xb0, 0x91, 0xd0, 0x7f, 0x00, 0x38, 0x5d, 0x51, 0x2e, 0xa2, 0x45, 0x4c,
	0xed, 0xd1, 0x41, 0xf3, 0xd0, 0xc2, 0x35, 0x04, 0xb9, 0xd0, 0x4d, 0xe9, 0xa5, 0xaa, 0x01, 0x49,
	0x03, 0xb3, 0xc5, 0xae, 0x7b, 0x4a, 0x2f, 0xa7, 0x1a, 0x9a, 0x35, 0x30, 0xa4, 0x95, 0x84, 0x9e,
	0x42, 0x4f, 0xa7, 0x2d, 0x4b, 0xb9, 0x2c, 0xb7, 0xdc, 0x33, 0x7b, 0x9a, 0x4b, 0x6c, 0xd6, 0xc0,
	0x5d, 0x7f, 0x2d, 0xa2, 0x37, 0x70, 0x33, 0xa7, 0xc2, 0x5b, 0x90, 0x38, 0xf6, 0xb2, 0x98, 0xf8,
	0x34, 0xa1, 0xa9, 0xf0, 0x32, 0x96, 0x9b, 0x03, 0x19, 0xbb, 0x73, 0x2a, 0x8e, 0x49, 0x1c, 0x9f,
	0x95, 0xca, 0x33, 0x96, 0xcf, 0x1a, 0x78, 0x2f, 0xbf, 0x0e, 0xa3, 0x67, 0x30, 0x24, 0x41, 0xe0,
	0x5d, 0xd1, 0x38, 0x66, 0x97, 0x9e, 0x4f, 0x78, 0x60, 0x8e, 0x6c, 0xe0, 0xbe, 0x08, 0x82, 0x5f,
	0x15, 0x3c, 0x25, 0x5c, 0xa6, 0xdd, 0x27, 0x75, 0x00, 0x4d, 0xa0, 0x27, 0x3d, 0x39, 0x0d, 0xb4,
	0x5b, 0xdb, 0x6c, 0xf5, 0x45, 0x10, 0x60, 0x1a, 0x18, 0x1f, 0x20, 0x95, 0x84, 0x9e, 0xc3, 0xa8,
	0x16, 0xc6, 0x63, 0x2b, 0xca, 0xed, 0x1d, 0xe5, 0x34, 0x74, 0xd7, 0xeb, 0xfe, 0xb4, 0xa2, 0x7c,
	0xd6, 0xc0, 0x83, 0xab, 0x0d, 0x04, 0x7d, 0x03, 0x03, 0x19, 0x6d, 0x7d, 0x5f, 0x6d, 0x4b, 0xb9,
	0xf6, 0x65, 0xbc, 0x57, 0x24, 0xa1, 0x3f, 0x4a, 0x70, 0xd6, 0xc0, 0x32, 0xa9, 0x4a, 0x46, 0xa7,
	0x70, 0x4b, 0xba, 0x65, 0x9c, 0x65, 0x2c, 0xa7, 0x1b, 0xfe, 0x1d, 0xe5, 0xbf, 0x2f, 0xfd, 0xcf,
	0x8c, 0xba, 0xbe, 0xce, 0x98, 0x7c, 0x04, 0x47, 0xaf, 0x60, 0x9c, 0x0b, 0xc2, 0x3f, 0x3c, 0x7d,
	0x1b, 0xd4, 0x62, 0x7b, 0xf2, 0xa6, 0xf2, 0xcd, 0x43, 0x9e, 0x35, 0x30, 0xca, 0xaf, 0xa1, 0xe8,
	0x33, 0xb0, 0x7c, 0x96, 0x8a, 0x28, 0x2d, 0xa8, 0xdd, 0x55, 0xce, 0x1d, 0x77, 0x6a, 0x80, 0x59,
	0x03, 0x57, 0x4a, 0xf4, 0x35, 0xf4, 0x8b, 0x2c, 0x90, 0x2d, 0xe3, 0xb3, 0x34, 0x8c, 0x96, 0x76,
	0xcf, 0xec, 0xfb, 0x67, 0x85, 0x4e, 0x15, 0x28, 0xf7, 0x5d, 0xd4, 0x64, 0xf4, 0x03, 0xec, 0x1a,
	0x2f, 0x41, 0x49, 0xa2, 0xc7, 0x84, 0xdd, 0x57, 0x9e, 0x23, 0xe3, 0xf9, 0x8e, 0x92, 0x44, 0x35,
	0xd6, 0xac, 0x81, 0x87, 0xc5, 0x26, 0x24, 0xa3, 0xe6, 0x97, 0x91, 0xf0, 0xcf, 0x3d, 0x9f, 0xc5,
	0x8c, 0xe7, 0xf6, 0xc0, 0x44, 0x9d, 0x2b, 0x74, 0xaa, 0x40, 0x19, 0x35, 0xaf, 0xc9, 0xe8, 0xbf,
	0xd0, 0xd6, 0xad, 0x60, 0x0f, 0x4d, 0x6b, 0x62, 0x25, 0xce, 0x1a, 0xd8, 0x28, 0x64, 0x1d, 0x65,
	0x7f, 0xa8, 0x3a, 0xe8, 0xac, 0x76, 0xcd, 0xca, 0xa7, 0xf4, 0x52, 0x9e, 0x73, 0x99, 0x52, 0x2f,
	0xad, 0xc9, 0xe8, 0x3d, 0xdc, 0x25, 0xbe, 0x4f, 0x33, 0x51, 0xab, 0xa0, 0xa9, 0x2a, 0x89, 0x73,
	0x1b, 0xa9, 0x35, 0x6e, 0xbb, 0x2f, 0x94, 0x4d, 0x55, 0xae, 0xb3, 0xd2, 0x60, 0xd6, 0xc0, 0x36,
	0xf9, 0x84, 0xee, 0xd8, 0x2a, 0x07, 0x8a, 0xf3, 0x04, 0x60, 0xdd, 0xa8, 0xc8, 0x81, 0x9d, 0xb2,
	0x8d, 0x9b, 0x6a, 0x7d, 0xcb, 0x35, 0x2a, 0x5c, 0x2a, 0x9c, 0xef, 0xa1, 0x5b, 0xeb, 0x54, 0xf4,
	0x25, 0x74, 0xe4, 0xee, 0x74, 0x2b, 0x4b, 0xa7, 0xc1, 0xd1, 0xc0, 0xc5, 0x7a, 0x94, 0xba, 0xca,
	0x04, 0x5b, 0x29, 0xbd, 0x54, 0x7f, 0xce, 0x53, 0xd8, 0xfb, 0x48, 0xa3, 0xa2, 0x3b, 0xb0, 0x2d,
	0x7b, 0xb9, 0x0c, 0xf9, 0x0b, 0xf5, 0x05, 0xe3, 0x47, 0x58, 0x82, 0x4e, 0x0a, 0xfd, 0x8d, 0xae,
	0x44, 0x07, 0x60, 0x85, 0x8c, 0xab, 0x22, 0x9b, 0x78, 0x2d, 0x57, 0x56, 0x11, 0xef, 0x84, 0x8c,
	0xcb, 0x1f, 0xf4, 0x1c, 0xc6, 0x3e, 0x29, 0xe4, 0xdd, 0x5f, 0x5c, 0xd5, 0xaf, 0xbf, 0x9e, 0x4c,
	0xe0, 0x56, 0x07, 0x82, 0x77, 0xb5, 0xdd, 0xf1, 0x55, 0x05, 0x39, 0x17, 0x00, 0xeb, 0x76, 0xfe,
	0xb7, 0x83, 0x1d, 0xc1, 0x60, 0x73, 0x0c, 0xfc, 0x7d, 0x40, 0xe7, 0x3b, 0xe8, 0xd5, 0xfb, 0x1f,
	0x7d, 0x0e, 0x50, 0x0b, 0xdb, 0xbc, 0x16, 0xb6, 0xb3, 0xac, 0xc2, 0x9d, 0xc0, 0xf8, 0x63, 0xad,
	0x8f, 0x5c, 0xb0, 0xca, 0x8b, 0x65, 0x16, 0x40, 0xee, 0xb5, 0x5b, 0x83, 0x2b, 0x1b, 0xe7, 0x2d,
	0xd8, 0x9f, 0xba, 0x76, 0xe8, 0x09, 0x74, 0xd6, 0x97, 0xb4, 0x79, 0xb0, 0xfd, 0x89, 0xc5, 0xd6,
	0x46, 0xce, 0x18, 0xd0, 0xf5, 0x19, 0xe2, 0x00, 0x58, 0xe5, 0x70, 0x70, 0x7e, 0x6b, 0x42, 0xaf,
	0xde, 0xfb, 0xe8, 0x21, 0x58, 0x41, 0xb4, 0x8a, 0xf2, 0x88, 0xa5, 0xe6, 0x94, 0x3a, 0xee, 0x4b,
	0x03, 0xe0, 0x4a, 0x85, 0xbe, 0x02, 0x14, 0x46, 0x3c, 0x17, 0xde, 0x45, 0xe4, 0x5f, 0xb0, 0x30,
	0xd4, 0xc7, 0xba, 0x55, 0x3f, 0xd6, 0x91, 0x32, 0x78, 0xa3, 0xf5, 0xaa, 0xa0, 0x0f, 0xa0, 0x4f,
	0x0a, 0xc1, 0xbc, 0x6a, 0x56, 0x6d, 0x2b, 0xc6, 0xeb, 0x49, 0xb0, 0xca, 0xe8, 0x8f, 0x1b, 0x30,
	0xfc, 0x60, 0xa6, 0xfc, 0x83, 0xbb, 0x72, 0x17, 0x3a, 0x6a, 0x36, 0xa5, 0x24, 0xd1, 0x4f, 0x81,
	0x0e, 0xb6, 0x24, 0x70, 0x4a, 0x12, 0x8a, 0xc6, 0xd0, 0x5a, 0x32, 0x79, 0x68, 0xdb, 0xea, 0xe9,
	0xa0, 0x05, 0x49, 0xbe, 0xf2, 0xe7, 0x82, 0xd2, 0x8c, 0x72, 0xc5, 0x76, 0x2d, 0x5c, 0x43, 0x64,
	0xb6, 0x92, 0xcc, 0x59, 0x21, 0x72, 0x2f, 0xa6, 0xa1, 0x50, 0x54, 0xd6, 0xc2, 0xbd, 0x12, 0x7c,
	0x4b, 0x43, 0x81, 0xbe, 0x80, 0x5d, 0x23, 0x7b, 0xf2, 0xab, 0x0d, 0xdb, 0x2a, 0xfe, 0xd0, 0x28,
	0xe4, 0xe3, 0x40, 0xd9, 0x1e, 0xc2, 0x88, 0xa5, 0x92, 0x5a, 0x23, 0x11, 0xad, 0xa8, 0x77, 0x4e,
	0xe2, 0x50, 0x51, 0x96, 0x85, 0x07, 0x2c, 0x3d, 0x33, 0xf0, 0x8c, 0xc4, 0x21, 0xfa, 0x16, 0x6e,
	0x7d, 0x40, 0xc8, 0x21, 0x89, 0xe2, 0x82, 0xd3, 0x5c, 0x11, 0x55, 0x0b, 0xef, 0x2f, 0xea, 0x15,
	0x3d, 0x31, 0x4a, 0xf4, 0x3f, 0x18, 0xf8, 0x24, 0xd5, 0x6e, 0x8a, 0x54, 0x14, 0x2f, 0x59, 0xb8,
	0xe7, 0x93, 0x54, 0x59, 0xcb, 0x8b, 0xa0, 0x56, 0x67, 0xc2, 0xcb, 0x8b, 0x45, 0x2e, 0x22, 0x51,
	0x88, 0x88, 0xa5, 0x5e, 0x94, 0x8a, 0x92, 0x79, 0x2c, 0xbc, 0xbf, 0x60, 0x62, 0x5e, 0xd3, 0xbe,
	0x56, 0x4a, 0xf4, 0x08, 0xba, 0x75, 0x66, 0xef, 0x1a, 0x8a, 0x5e, 0xb7, 0x19, 0x86, 0x35, 0xcf,
	0xa2, 0x07, 0x60, 0x55, 0x6c, 0xde, 0x33, 0xe3, 0xc7, 0xf4, 0x3e, 0xde, 0xe1, 0x66, 0x08, 0xdc,
	0x86, 0x1b, 0x21, 0x2b, 0x62, 0x43, 0x26, 0x2d, 0xf7, 0x84, 0x15, 0x31, 0x56, 0x10, 0x7a, 0x04,
	0x88, 0xd3, 0x84, 0xad, 0xe8, 0xc6, 0x73, 0x42, 0x32, 0x47, 0x1f, 0x8f, 0xb4, 0xa6, 0x36, 0xba,
	0xfe, 0x0f, 0x43, 0x63, 0x5d, 0x05, 0x1d, 0x2a, 0xd3, 0xbe, 0x86, 0xcb, 0xa9, 0x73, 0x1f, 0xba,
	0xc6, 0x4e, 0xc5, 0x1d, 0x29, 0x1b, 0xd0, 0x90, 0x0c, 0xee, 0x0c, 0xa0, 0x57, 0x67, 0x25, 0xe7,
	0x21, 0xb4, 0x35, 0xed, 0xc8, 0x2b, 0x66, 0x1e, 0x57, 0xd5, 0x23, 0xd4, 0xd2, 0xc0, 0xeb, 0x40,
	0x8e, 0x8e, 0x3a, 0xe5, 0x54, 0xa3, 0x43, 0xb3, 0x52, 0x7d, 0x74, 0xe8, 0xe7, 0xa7, 0x1a, 0x1d,
	0xea, 0xf7, 0xf8, 0xe4, 0xfd, 0xcb, 0x65, 0x24, 0xce, 0x8b, 0x85, 0xeb, 0xb3, 0x64, 0x82, 0xd9,
	0x82, 0x4d, 0x8b, 0xec, 0xf1, 0x7c, 0xfe, 0x76, 0x92, 0xe7, 0xf1, 0x63, 0x69, 0xf7, 0x58, 0x36,
	0x0c, 0x67, 0x71, 0x4c, 0xf9, 0x44, 0x16, 0x8a, 0xa7, 0x24, 0x9e, 0x90, 0x2c, 0x9b, 0xa8, 0xd5,
	0x13, 0xe2, 0x9f, 0x47, 0x29, 0xfd, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x95, 0x2e, 0xb7, 0xb3, 0xdb,
	0x0b, 0x00, 0x00,
}
